var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var Mod = (function (_super) {
    __extends(Mod, _super);
    function Mod() {
        _super.apply(this, arguments);
    }
    Mod.prototype.onInitialize = function () {
        var chinese = new Languages.Language("中文");
// UI
chinese.ui(Languages.UiTranslation.Bleeding, "流血中");
chinese.ui(Languages.UiTranslation.Burned, "烧伤");
chinese.ui(Languages.UiTranslation.DisableHints, "禁用提示");
chinese.ui(Languages.UiTranslation.EnableHints, "开启提示");
chinese.ui(Languages.UiTranslation.EquipmentBack, "背部");
chinese.ui(Languages.UiTranslation.EquipmentBelt, "腰带");
chinese.ui(Languages.UiTranslation.EquipmentChest, "胸部");
chinese.ui(Languages.UiTranslation.EquipmentFeet, "双脚");
chinese.ui(Languages.UiTranslation.EquipmentHands, "双手");
chinese.ui(Languages.UiTranslation.EquipmentHead, "头部");
chinese.ui(Languages.UiTranslation.EquipmentLeftHand, "左手 (持有)");
chinese.ui(Languages.UiTranslation.EquipmentLegs, "腿部");
chinese.ui(Languages.UiTranslation.EquipmentNeck, "颈部");
chinese.ui(Languages.UiTranslation.EquipmentRightHand, "右手 (持有)");
chinese.ui(Languages.UiTranslation.Health, "健康 (生命值)");
chinese.ui(Languages.UiTranslation.HudActions, "行动");
chinese.ui(Languages.UiTranslation.HudCrafting, "制作");
chinese.ui(Languages.UiTranslation.HudEquipment, "装备");
chinese.ui(Languages.UiTranslation.HudFilter, "过滤");
chinese.ui(Languages.UiTranslation.HudHelp, "帮助");
chinese.ui(Languages.UiTranslation.HudInventory, "库存");
chinese.ui(Languages.UiTranslation.HudMessages, "消息");
chinese.ui(Languages.UiTranslation.HudMilestones, "里程碑");
chinese.ui(Languages.UiTranslation.HudOptions, "设置");
chinese.ui(Languages.UiTranslation.HudSave, "保存");
chinese.ui(Languages.UiTranslation.HudSkills, "技能");
chinese.ui(Languages.UiTranslation.HudTitleScreen, "主菜单");
chinese.ui(Languages.UiTranslation.Hunger, "饥饿");
chinese.ui(Languages.UiTranslation.Malignity, "恶意");
chinese.ui(Languages.UiTranslation.MenuAbout, "关于");
chinese.ui(Languages.UiTranslation.MenuAboutCredits, "Vaughn 'Drathy' Royko (程序/网络/公关/设计),Gary 'Spacetech' Wilber (程序),Frank 'Sassafrass' Sasto (程序),Dusty 'Goaticide' Melling (艺术/设计),Austin Dhillon (音乐)");
chinese.ui(Languages.UiTranslation.MenuAboutDonators, "特别感谢所有早期测试玩家、捐助者和其他支持者！");
chinese.ui(Languages.UiTranslation.MenuAboutIntro, "Wayward 是回合制的野外生存Roguelike游戏，目前处于Beta阶段，诞生于这些优秀的民间制作者:");
chinese.ui(Languages.UiTranslation.MenuAboutLibraries, "Greenworks, Electron, TypeScript, Node.js, jQuery, jQueryUI, TSM, lz-string, jQuery contextMenu, jQuery UI Touch Punch, Pluralize, Fixedsys Excelsior");
chinese.ui(Languages.UiTranslation.MenuAboutLibrariesIntro, "Wayward由以下工具编写:");
chinese.ui(Languages.UiTranslation.MenuAboutMessage, "更多关于Wayward的信息");
chinese.ui(Languages.UiTranslation.MenuAboutThanks, "Richard 'Orillian' Hobson,Vlad 'vlsd' Seghete,Unstoppable Carl Olsen,Justin 'boxofrox' Charette,Frank Orechio,Drachlen,Joshua 'jday' Day,Oddmund 'oddmunds' Strømme");
chinese.ui(Languages.UiTranslation.MenuAboutThanksIntro, "特别感谢:");
chinese.ui(Languages.UiTranslation.MenuDailyChallenge, "每日挑战");
chinese.ui(Languages.UiTranslation.MenuDeleteAllGameData, "删除所有存档");
chinese.ui(Languages.UiTranslation.MenuDeleteGame, "删除游戏");
chinese.ui(Languages.UiTranslation.MenuEditGame, "编辑名字");
chinese.ui(Languages.UiTranslation.MenuEndGameDead, "你已经死亡");
chinese.ui(Languages.UiTranslation.MenuEndGameWon, "你胜利了");
chinese.ui(Languages.UiTranslation.MenuExportGame, "导出游戏");
chinese.ui(Languages.UiTranslation.MenuExportSave, "导出存档");
chinese.ui(Languages.UiTranslation.MenuImportGame, "导入游戏");
chinese.ui(Languages.UiTranslation.MenuImportSave, "导入存档");
chinese.ui(Languages.UiTranslation.MenuManageMods, "管理模组(Mods)");
chinese.ui(Languages.UiTranslation.MenuManageModsInternal, "内置模组(Mods)");
chinese.ui(Languages.UiTranslation.MenuManageModsLocal, "内置模组(Mods)");
chinese.ui(Languages.UiTranslation.MenuManageModsMessage, "从 Steam WorkShop 安装模组(Mods)");
chinese.ui(Languages.UiTranslation.MenuManageModsPublishMod, "发行模组(Mods)");
chinese.ui(Languages.UiTranslation.MenuManageModsUninstallMod, "卸载模组(Mods)");
chinese.ui(Languages.UiTranslation.MenuManageModsViewInSteamWorkshop, "浏览 Steam Workshop 页面");
chinese.ui(Languages.UiTranslation.MenuManageModsWorkshop, "Workshop模组(Mods)");
chinese.ui(Languages.UiTranslation.MenuModdingGuide, "模组(Mods)开发指南");
chinese.ui(Languages.UiTranslation.MenuNoHighscores, "没有高分记录");
chinese.ui(Languages.UiTranslation.MenuNoMods, "你没有安装模组(Mods)");
chinese.ui(Languages.UiTranslation.MenuOpenLogsFolder, "打开日志 (Log) 目录");
chinese.ui(Languages.UiTranslation.MenuOpenModsFolder, "打开模组 (Mods) 目录");
chinese.ui(Languages.UiTranslation.MenuOptions, "设置");
chinese.ui(Languages.UiTranslation.MenuOptionsMessage, "改变你的游戏设置");
chinese.ui(Languages.UiTranslation.MenuPlayGame, "开始游戏");
chinese.ui(Languages.UiTranslation.MenuPlayGameMessage, "继续或者创建新游戏");
chinese.ui(Languages.UiTranslation.MenuPlayGameNewGame, "新游戏");
chinese.ui(Languages.UiTranslation.MenuPostATweet, "分享至Twitter");
chinese.ui(Languages.UiTranslation.MenuQuitGame, "离开游戏");
chinese.ui(Languages.UiTranslation.MenuReloadGame, "重启游戏");
chinese.ui(Languages.UiTranslation.MenuShareOnFacebook, "分享至Facebook");
chinese.ui(Languages.UiTranslation.MenuToggleDeveloperTools, "切换开发者工具");
chinese.ui(Languages.UiTranslation.MenuViewHighscores, "浏览高分记录");
chinese.ui(Languages.UiTranslation.MenuViewHighscoresMessage, "之前在游戏中的死亡记录");
chinese.ui(Languages.UiTranslation.MenuVisitSteamWorkshop, "参观Steam Workshop");
chinese.ui(Languages.UiTranslation.NextHint, "下一个提示");
chinese.ui(Languages.UiTranslation.OptionsAlternateContextMenu, "右键显示菜单");
chinese.ui(Languages.UiTranslation.OptionsAlternateContextMenuTooltip, "如果选中，右键项目将显示项目的菜单，而不是左键显示。");
chinese.ui(Languages.UiTranslation.OptionsAlternateFont, "正常字体");
chinese.ui(Languages.UiTranslation.OptionsAudio, "音效");
chinese.ui(Languages.UiTranslation.OptionsAudio, "音效");
chinese.ui(Languages.UiTranslation.OptionsAutoGather, "自动收集");
chinese.ui(Languages.UiTranslation.OptionsAutoGatherTooltip, "如果选中，移动到资源时将自动收集。");
chinese.ui(Languages.UiTranslation.OptionsAutoPickup, "自动捡起");
chinese.ui(Languages.UiTranslation.OptionsAutoPickupTooltip, "如果选中，移动到物品时将自动捡起。");
chinese.ui(Languages.UiTranslation.OptionsDeveloper, "开发选项");
chinese.ui(Languages.UiTranslation.OptionsDialogOpacity, "窗口透明度");
chinese.ui(Languages.UiTranslation.OptionsDropOnGather, "自动丢弃");
chinese.ui(Languages.UiTranslation.OptionsDropOnGatherTooltip, "如果选中，你捡起物品时如果背包满将自动丢弃物品。");
chinese.ui(Languages.UiTranslation.OptionsEffects, "声效");
chinese.ui(Languages.UiTranslation.OptionsEnableHints, "开启提示");
chinese.ui(Languages.UiTranslation.OptionsEnableHintsTooltip, "如果选中，将显示游戏帮助提示。");
chinese.ui(Languages.UiTranslation.OptionsFullscreenMode, "全屏模式");
chinese.ui(Languages.UiTranslation.OptionsGame, "游戏");
chinese.ui(Languages.UiTranslation.OptionsGraphics, "画面");
chinese.ui(Languages.UiTranslation.OptionsKeepSortActive, "自动分类");
chinese.ui(Languages.UiTranslation.OptionsKeepSortActiveTooltip, "如果选中，库存的物品将会自动分类。");
chinese.ui(Languages.UiTranslation.OptionsBindDefault, "默认");
chinese.ui(Languages.UiTranslation.OptionsKeyBindRebinding, "按任意键...");
chinese.ui(Languages.UiTranslation.OptionsBinds, "按键设置");
chinese.ui(Languages.UiTranslation.OptionsLanguage, "语言");
chinese.ui(Languages.UiTranslation.OptionsMouseClickMovement, "鼠标移动");
chinese.ui(Languages.UiTranslation.OptionsMouseClickMovementTooltip, "如果选中，你可以通过鼠标移动你的人物。");
chinese.ui(Languages.UiTranslation.OptionsMusic, "音乐");
chinese.ui(Languages.UiTranslation.OptionsMute, "静音");
chinese.ui(Languages.UiTranslation.OptionsNextSong, "试听");
chinese.ui(Languages.UiTranslation.OptionsPixelFont, "像素字体");
chinese.ui(Languages.UiTranslation.OptionsSaveData, "存档选项");
chinese.ui(Languages.UiTranslation.OptionsScaleDefault, "默认");
chinese.ui(Languages.UiTranslation.OptionsScaleIn, "缩放界面 +");
chinese.ui(Languages.UiTranslation.OptionsScaleOut, "缩放界面 -");
chinese.ui(Languages.UiTranslation.OptionsSkipIntro, "跳过画面");
chinese.ui(Languages.UiTranslation.OptionsSkipIntroTooltip, "如果勾选，将跳过启动画面。");
chinese.ui(Languages.UiTranslation.OptionsVisionDither, "抖动视觉");
chinese.ui(Languages.UiTranslation.OptionsVisionFade, "平淡视觉");
chinese.ui(Languages.UiTranslation.OptionsWindowedMode, "窗口模式");
chinese.ui(Languages.UiTranslation.OptionsWorldTooltips, "世界提示");
chinese.ui(Languages.UiTranslation.OptionsWorldTooltipsTooltip, "如果选中，悬停在不是空白的区域时你不用检查会自动显示提示信息。");
chinese.ui(Languages.UiTranslation.OptionsZoomIn, "放大");
chinese.ui(Languages.UiTranslation.OptionsZoomOnScroll, "滚轮缩放");
chinese.ui(Languages.UiTranslation.OptionsZoomOnScrollTooltip, "如果选中，你可以使用鼠标滚轮/缩放手势来缩放游戏。");
chinese.ui(Languages.UiTranslation.OptionsZoomOut, "缩小");
chinese.ui(Languages.UiTranslation.Poisoned, "中毒");
chinese.ui(Languages.UiTranslation.PreviousHint, "上一个提示");
chinese.ui(Languages.UiTranslation.QuickSlot1, "1");
chinese.ui(Languages.UiTranslation.QuickSlot2, "2");
chinese.ui(Languages.UiTranslation.QuickSlot3, "3");
chinese.ui(Languages.UiTranslation.QuickSlot4, "4");
chinese.ui(Languages.UiTranslation.QuickSlot5, "5");
chinese.ui(Languages.UiTranslation.QuickSlot6, "6");
chinese.ui(Languages.UiTranslation.QuickSlot7, "7");
chinese.ui(Languages.UiTranslation.QuickSlot8, "8");
chinese.ui(Languages.UiTranslation.QuickSlot9, "9");
chinese.ui(Languages.UiTranslation.ReturnToTitleScreen, "回到主菜单");
chinese.ui(Languages.UiTranslation.Stamina, "耐力(敏捷)");
chinese.ui(Languages.UiTranslation.Thirst, "水分");
chinese.ui(Languages.UiTranslation.Version, `Wayward Beta ${gameVersion}`);
chinese.ui(Languages.UiTranslation.Weight, "重量(强度)");
chinese.ui(Languages.UiTranslation.WindowTitleContainer, "容器");
chinese.ui(Languages.UiTranslation.WindowTitleCrafting, "制作");
chinese.ui(Languages.UiTranslation.WindowTitleEquipment, "装备");
chinese.ui(Languages.UiTranslation.WindowTitleHighscores, "高分");
chinese.ui(Languages.UiTranslation.WindowTitleInventory, "库存");
chinese.ui(Languages.UiTranslation.WindowTitleMap, "地图");
chinese.ui(Languages.UiTranslation.WindowTitleMessages, "消息");
chinese.ui(Languages.UiTranslation.WindowTitleMilestones, "里程碑");
chinese.ui(Languages.UiTranslation.WindowTitleOptions, "设置");
chinese.ui(Languages.UiTranslation.WindowTitleSkills, "技能");

// Messages
// NOTE: Style guide
// No contractions for in-game messages (other UI/dialogs can use them)
// Past tense for all messages that appear when/during taking a turn
// Present tense for all messages that appear when no turn is passed
// For the style guide of the enum names, check enums.ts
chinese.message(Message.AberrantCreatureDroppedItem, "神奇的事情发生了, 这个奇怪的生物掉落了_0_.");
chinese.message(Message.AboutHours, "你似乎拥有了_0_大概_1_ _2_.");
chinese.message(Message.AddedFuelToFire, "你往火里添加了燃料! 火变得更旺了.");
chinese.message(Message.AddedFuelToTorch, "你往火把里添加了燃料.");
chinese.message(Message.AddFuel, "添加燃料");
chinese.message(Message.AddToQuickslot, "放入快捷栏");
chinese.message(Message.Advanced, "高级");
chinese.message(Message.AlreadyFullyRepaired, "_0_已经完全修复.");
chinese.message(Message.AlreadyWaterInStill, "这个蒸馏器里已经有水了!");
chinese.message(Message.AppearsToBeDawn, "现在是黎明.");
chinese.message(Message.AppearsToBeDusk, "现在是黄昏.");
chinese.message(Message.AppearsToBeMidDay, "现在是中午.");
chinese.message(Message.AppearsToBeNight, "现在是晚上");
chinese.message(Message.AreYouSureYouWantToSail, "你确定你要向着文明世界起航吗? 你的旅程将会结束, 但是你还是可以随时返回到这些地方.");
chinese.message(Message.ArmorAppearedResistant, "你的盔甲抵抗了攻击.");
chinese.message(Message.ArmorAppearedVulnerable, "你的盔甲容易受到攻击.");
chinese.message(Message.ArmorProtectedFromInjuryAgainst, "你的盔甲保护了你免受_0_点伤害.");
chinese.message(Message.Attack, "攻击");
chinese.message(Message.AttemptedToDropAllIntoFire, "你尝试把所有的_0_扔到火里.");
chinese.message(Message.AttemptToPlaceAllOnGround, "你尝试把所有的_0_在地上.");
chinese.message(Message.AutomaticallySavingGame, "正在自动保存你的游戏...");
chinese.message(Message.AwakeToFindYourself, "你醒来发现自己不是在公司也没有在航海船上. 并发现了自己衣衫褴褛, 拿着个满是简陋工具的口袋. 财宝... 你记得一些关于宝藏的事情.");
chinese.message(Message.Back, "背部");
chinese.message(Message.BadlyBurnedLostHealth, "你被严重烧伤! 你掉了_0_点血!");
chinese.message(Message.BeenPoisoned, "你中毒了!");
chinese.message(Message.BeginSleeping, "你开始睡觉...");
chinese.message(Message.BeginUsingRaft, "你开始使用木筏.");
chinese.message(Message.Belt, "腰带");
chinese.message(Message.BleedingHasStopped, "你停止掉血!");
chinese.message(Message.BleedingProfusely, "你开始大量掉血!");
chinese.message(Message.BleedingToDeathLostHealth, "你快因为掉血而死了! 你掉了_0_点血!");
chinese.message(Message.Blunt, "钝器");
chinese.message(Message.BrokeIntoPieces, "_0_已经没办法修理并且化成了碎片.");
chinese.message(Message.BrokenOnImpact, "_0_因为冲击而坏掉了!");
chinese.message(Message.BrokenWhileFiring, "_0_被火烧坏了!");
chinese.message(Message.Build, "建筑");
chinese.message(Message.Burned, "烧毁");
chinese.message(Message.By, "因为 ");
chinese.message(Message.ByBleedingOut, "因为掉血");
chinese.message(Message.ByBurnInjuries, "因为你的烧伤");
chinese.message(Message.ByEatingSomethingBad, "因为吃了对你有害的东西");
chinese.message(Message.ByPoisoning, "因为中毒");
chinese.message(Message.BySteppingOnA, "因为踩在了");
chinese.message(Message.BySteppingOnTrap, "因为踩中陷阱");
chinese.message(Message.ByWorkingYourselfIntoExhaustion, "因为过度劳累");
chinese.message(Message.Cancel, "取消");
chinese.message(Message.CannotAddAnyMoreFuel, "你不能再添加燃料到_0_.");
chinese.message(Message.CannotBePerformedOverWater, "此操作不能在水上执行.");
chinese.message(Message.CannotBePreserved, "这个东西不能防腐加工.");
chinese.message(Message.CannotBeReinforced, "_0_不能被加固.");
chinese.message(Message.CannotBeRepaired, "_0_不能被修理.");
chinese.message(Message.CannotBeTransmogrified, "_0_不能被改变性质.");
chinese.message(Message.CannotBuildHere, "你不能在这里建立_0_!");
chinese.message(Message.CannotDigHere, "你不能挖这里!");
chinese.message(Message.CannotDropHere, "你不能在这里扔下_0_!");
chinese.message(Message.CannotEquipThatThere, "你不能把那个装备到那里!");
chinese.message(Message.CannotFishFor, "你不能在_0_钓鱼.");
chinese.message(Message.CannotGatherFromWhileOnFire, "当它在燃烧的时候,你不能拿起来!");
chinese.message(Message.CannotGatherHere, "你在这里收集不到任何东西.");
chinese.message(Message.CannotImproveGrowingSpeed, "你没办法对这个植物的成长速度再进行改进.");
chinese.message(Message.CannotInWater, "你不能在水里_0_东西.");
chinese.message(Message.CannotPickupWhenFull, "当它充满水的时候,你没办法捡起来.");
chinese.message(Message.CannotPickUpWhileLit, "当它还点燃的时候,你没办法捡起来.");
chinese.message(Message.CannotPickUpWithItemsInside, "当它里面还有东西的时候,你没办法捡起来!");
chinese.message(Message.CannotPlaceContainerInItself, "你不能把容器放到它里面.");
chinese.message(Message.CannotPlaceHere, "你不能把_0_放在这里!");
chinese.message(Message.CannotPlaceThatFromHere, "你不能从这里把那个放下.");
chinese.message(Message.CannotPlaceThatHere, "你不能把那个放在这里.");
chinese.message(Message.CannotPlantHere, "你不能把_0_种在这里!");
chinese.message(Message.CannotRepairWhileLit, "你不能在它还点燃的时候进行修复!");
chinese.message(Message.CannotRestHere, "你不能在这里休息.");
chinese.message(Message.CannotSeeHere, "你在这里看不到任何东西.");
chinese.message(Message.CannotSleepHere, "你不能睡在这里.");
chinese.message(Message.CannotStartFireHere, "你不能在这里生火!");
chinese.message(Message.CannotToTellTime, "你不能从这里知道时间!");
chinese.message(Message.CarryingTooMuchWeight, "你背负了太重的东西!");
chinese.message(Message.CarvedUpCorpse, "你切割开了尸体.");
chinese.message(Message.CastYourLine, "你把鱼线投出了_0_格.");
chinese.message(Message.Category, "类别");
chinese.message(Message.CaughtFish, "你抓到了_0_!");
chinese.message(Message.Chest, "箱子");
chinese.message(Message.ClearMessages, "清除信息");
chinese.message(Message.CloseDoor, "关门");
chinese.message(Message.CollectObject, "用手收集");
chinese.message(Message.Consumed, "消耗");
chinese.message(Message.Container, "容器");
chinese.message(Message.Cook, "煮");
chinese.message(Message.Cooked, "煮熟的");
chinese.message(Message.Corpse, "尸体");
chinese.message(Message.CorruptSaveDetected, "检测到受损的存档.此存档可能无法正确加载.");
chinese.message(Message.CouldNotDecipher, "你没办法破译地图.");
chinese.message(Message.Craft, "制作");
chinese.message(Message.Crafted, "制作了");
chinese.message(Message.Crafts, "手工制品");
chinese.message(Message.CreatureAppears, "_0_出现了!");
chinese.message(Message.CreatureAppearsHealthy, "它看起来很健康.");
chinese.message(Message.CreatureAppearsUnhealthy, "它看起来不太健康.");
chinese.message(Message.CreatureIsAtPercentHealth, "它还有_0_%的血.");
chinese.message(Message.CreatureLooksBarelyHurt, "它看起来几乎没有受伤.");
chinese.message(Message.CreatureLooksHealthyAndUndamaged, "它看起来很健康而且相当完好.");
chinese.message(Message.CreatureLooksInjured, "它看起来受伤了.");
chinese.message(Message.CreatureLooksSeverelyDamaged, "它看起来受伤严重.");
chinese.message(Message.CreatureSeemsHurt, "它似乎受伤了.");
chinese.message(Message.CreatureSeemsInjured, "它似乎受伤严重.");
chinese.message(Message.CreatureSeemsUnimpaired, "它似乎未受损害.");
chinese.message(Message.CuredYourPoison, "你把中毒治好了!");
chinese.message(Message.Cut, "切开");
chinese.message(Message.DailyChallengeMode, "每日挑战模式");
chinese.message(Message.DamageAppearedEffective, "_0_的伤害生效了.");
chinese.message(Message.DamageAppearedIneffective, "_0_的伤害没有生效.");
chinese.message(Message.DamagedByPouringWater, "你用泼水对_0_造成了伤害.");
chinese.message(Message.DealtNoDamageToYou, "_0_对你没有造成任何伤害.");
chinese.message(Message.Decay, "腐坏");
chinese.message(Message.DefaultGameName, "未命名存档_0_");
chinese.message(Message.DependencyIssue, "依赖问题.");
chinese.message(Message.DestroyedFromUse, "_0_被用坏了.");
chinese.message(Message.DestroyedGrowingByPickingItUp, "你损坏了_0_作物, 在你尝试捡起_1_的时候!");
chinese.message(Message.DexterityIncreasing, "你感觉你的敏捷增加了!");
chinese.message(Message.DidNotSeemToBeHurting, "_0_没法对_1_产生伤害.");
chinese.message(Message.Disassemble, "分解");
chinese.message(Message.DisassembleAction, "分解");
chinese.message(Message.DiscoveredCaveEntrance, "你发现了洞穴入口!");
chinese.message(Message.DiscoveredInTheBottle, "你在瓶子里发现了_0_!");
chinese.message(Message.Dismantle, "分解");
chinese.message(Message.DismantleAction, "分解");
chinese.message(Message.DismantleLabel, "分解: ");
chinese.message(Message.DismantlingRequires, "分解这个需要_0_.");
chinese.message(Message.DoNotForgetToAddRequiredModsOnWorkshop, "别忘了在steam商店添加mod哦!");
chinese.message(Message.DoNotHaveTreasureMaps, "你并没有藏宝图!");
chinese.message(Message.DoodadAppearsDamaged, "它受过一次非常大的伤害.");
chinese.message(Message.DoodadAppearsOnVergeOfBreaking, "它快要破碎了.");
chinese.message(Message.DoodadAppearsUnscathed, "它处于正常的状态.");
chinese.message(Message.DoodadCauseStatus, "_0_对你_1_. 你掉了_2_点血!");
chinese.message(Message.DoodadShowsSignsOfWear, "它有点磨损的样子.");
chinese.message(Message.DrewSurroundings, "你放在了脚边.");
chinese.message(Message.Drink, "喝");
chinese.message(Message.Drop, "丢弃");
chinese.message(Message.DropAll, "丢弃全部同类物品");
chinese.message(Message.DropAllOfSameQuality, "把所有相同质量等级的丢弃");
chinese.message(Message.DroppedAllIntoDepths, "你把所有的_0_丢进了深海里.");
chinese.message(Message.DroppedIntoDepths, "你把_0_丢进了深海里.");
chinese.message(Message.DroppedIntoFire, "你把_0_丢进火里.");
chinese.message(Message.DueToDehydration, "由于脱水");
chinese.message(Message.DueToStarvation, "由于饥饿");
chinese.message(Message.DugTreasureOut, "你把宝藏挖出来了.");
chinese.message(Message.DumpContentsOfContainerInInventory, "你把容器里的东西放进了工具栏里!");
chinese.message(Message.Durability, "耐久性");
chinese.message(Message.DyingOfDehydration, "你快因为脱水而死掉了!");
chinese.message(Message.EarnedMilestone, "你已经赢得了里程碑,_0_!_1_");
chinese.message(Message.EquipTo, "放置到");
chinese.message(Message.ErrorHasOccured, "错误发生了!");
chinese.message(Message.Expert, "专家");
chinese.message(Message.ExtinguishedFire, "你熄灭了火.");
chinese.message(Message.ExtinguishedTorch, "你熄灭了火把.");
chinese.message(Message.FailedToAddFuelToTorch, "你没有正确地往火把里添加燃料.");
chinese.message(Message.FailedToCatchFish, "你抓鱼失败了!");
chinese.message(Message.FailedToCauseDamage, "你不能伤害_0_.当你使用_1_!_2_");
chinese.message(Message.FailedToDrawMap, "你绘制地图失败了.");
chinese.message(Message.FailedToPickLock, "你解锁失败了.");
chinese.message(Message.FailedToPlant, "你种植_0_的时候失败了.");
chinese.message(Message.FailedToPreserve, "你保存食物失败了.");
chinese.message(Message.FailedToReinforce, "你增强_0_失败了.");
chinese.message(Message.FailedToRepair, "你修复_0_失败了.");
chinese.message(Message.FailedToStartFire, "你生火失败了!");
chinese.message(Message.FailedToTransmogrify, "你改变_0_的属性失败了.");
chinese.message(Message.FarAwayFromTreasure, "你离财宝还很远.");
chinese.message(Message.Feet, "脚");
chinese.message(Message.FeltBurningPainLostHealth, "你感到被火烧的疼痛! 你掉了_0_点血!");
chinese.message(Message.FewMinutes, "你会_0_几分钟.");
chinese.message(Message.Filled, "你充满了_0_.");
chinese.message(Message.FilledFrom, "你充满_0_从_1_.");
chinese.message(Message.FinalizingWorld, "最后的世界");
chinese.message(Message.Fire, "火");
chinese.message(Message.FireAlmostExtinguished, "火几乎要熄灭了.");
chinese.message(Message.FiredIntoObstacle, "你把_0_烧成了灰.");
chinese.message(Message.FireFacingYouIsWarm, "你面前的火温暖又舒服.");
chinese.message(Message.FireIsHealthy, "火势很好.");
chinese.message(Message.FireIsRaging, "火势旺盛!");
chinese.message(Message.FireIsStruggling, "火在挣扎.");
chinese.message(Message.FireSource, "火源");
chinese.message(Message.FirstQuarterOfDay, "现在已经过了白天的四分之一.");
chinese.message(Message.FirstQuarterOfNight, "现在已经过了晚上的四分之一.");
chinese.message(Message.Food, "食物");
chinese.message(Message.FoodAlreadyPreserved, "这个食物被很好地防腐了.");
chinese.message(Message.FourthQuarterOfDay, "现在是白天的后四分之一.");
chinese.message(Message.FourthQuarterOfNight, "现在是晚上的后四分之一.");
chinese.message(Message.FullyDecodedMap, "你完全破译了地图!");
chinese.message(Message.GainedHealth, "你获得了 _0_ 点生命值.");
chinese.message(Message.GainedHunger, "你获得了 _0_ 点饱腹值.");
chinese.message(Message.GainedStamina, "你获得了 _0_ 点耐力.");
chinese.message(Message.GainedThirst, "你获得了 _0_ 点水分.");
chinese.message(Message.GameHasBeenSavedIsTakingUpMB, "你的游戏已保存! 你的游戏存档占用了_0_MB.");
chinese.message(Message.Gather, "收集");
chinese.message(Message.GeneratingWorld, "生成世界");
chinese.message(Message.GrabAll, "抓起全部");
chinese.message(Message.Group, "分组");
chinese.message(Message.Hands, "手");
chinese.message(Message.HasBeenHurtByATrap, "_0_被陷阱伤害了!");
chinese.message(Message.HasBeenHurtByYourTrap, "_0_被你的陷阱伤害了!");
chinese.message(Message.HasDecayed, "你的_0_腐坏了.");
chinese.message(Message.HasHitYouForDamage, "_0_攻击你造成_1_伤害!_2_");
chinese.message(Message.HasSplit, "_0_裂开了.");
chinese.message(Message.Head, "头");
chinese.message(Message.Held, "手上");
chinese.message(Message.Help, "帮助");
chinese.message(Message.Hints, "提示");
chinese.message(Message.HintsDisabled, "关闭提示.");
chinese.message(Message.HintsEnabled, "打开提示.");
chinese.message(Message.HitForDamage, "你对_0_造成_1_伤害用_2_!_3_");
chinese.message(Message.Hour, "小时");
chinese.message(Message.Hours, "小时");
chinese.message(Message.HowDoYouWantToExportSave, "你想导出这个存档吗?");
chinese.message(Message.HurtHandsByGatheringWithNoTool, "你的手因为没有使用工具进行收集而受伤了.");
chinese.message(Message.HurtHandsHittingWithoutWeapons, "你的手因为没有使用武器工具_0_而受伤了!");
chinese.message(Message.IncompatibleVersion, "这个mod不兼容这个版本的游戏.");
chinese.message(Message.InExactLocationOfTreasure, "你在宝藏埋藏的准确位置上.");
chinese.message(Message.InjuredFromTrap, "你被陷阱伤害了!");
chinese.message(Message.InNeedOfRepair, "_0_需要修复.");
chinese.message(Message.Inspect, "检查");
chinese.message(Message.Intermediate, "中级");
chinese.message(Message.Inventory, "工具栏");
chinese.message(Message.ItContains, "它包含了_0_.");
chinese.message(Message.ItsWeightCapacity, "它的重量是_0_ / _1_.");
chinese.message(Message.Jump, "跳跃");
chinese.message(Message.Killed, "杀死了_0_!");
chinese.message(Message.LabelAttackFromTactics, "战术进攻:");
chinese.message(Message.LabelAuthor, "作者: ");
chinese.message(Message.LabelBase, "基础: ");
chinese.message(Message.LabelBaseAttack, "基础攻击:");
chinese.message(Message.LabelBaseDefense, "基础防御:");
chinese.message(Message.LabelBluntResist, "钝击抵抗:");
chinese.message(Message.LabelDecay, "腐坏: ");
chinese.message(Message.LabelDefense, "防御:");
chinese.message(Message.LabelDefenseFromParrying, "格挡:");
chinese.message(Message.LabelDoodadRequired, "制作需要: ");
chinese.message(Message.LabelDurability, "耐久度: ");
chinese.message(Message.LabelEquip, "装备:");
chinese.message(Message.LabelFireResist, "抗火:");
chinese.message(Message.LabelGrouping, "分组: ");
chinese.message(Message.LabelHave, "持有: ");
chinese.message(Message.LabelHp, "生命: ");
chinese.message(Message.LabelLastUpdated, "最后更新于: ");
chinese.message(Message.LabelLeftHandAttack, "左手攻击:");
chinese.message(Message.LabelLevel, "等级: ");
chinese.message(Message.LabelMalignityNegative, "恶意值(-): ");
chinese.message(Message.LabelMalignityPlus, "恶意值(+): ");
chinese.message(Message.LabelOnEquip, "装备中: ");
chinese.message(Message.LabelPiercingResist, "穿刺抵抗:");
chinese.message(Message.LabelRange, "远程: ");
chinese.message(Message.LabelRanged, "远程: ");
chinese.message(Message.LabelRangedAttack, "远程攻击: ");
chinese.message(Message.LabelRangedDamage, "远程防御:");
chinese.message(Message.LabelRequiredMods, "所需的mod: ");
chinese.message(Message.LabelRequires, "需要: ");
chinese.message(Message.LabelResists, "抵抗: ");
chinese.message(Message.LabelRightHandAttack, "右手攻击:");
chinese.message(Message.LabelScore, "分数: ");
chinese.message(Message.LabelSkill, "技能: ");
chinese.message(Message.LabelSlashingResist, "劈砍抵抗:");
chinese.message(Message.LabelStokeFireStrength, "添火: ");
chinese.message(Message.LabelUse, "用途:");
chinese.message(Message.LabelUses, "用途:");
chinese.message(Message.LabelVersion, "版本: ");
chinese.message(Message.LabelVulnerabilities, "弱点: ");
chinese.message(Message.LabelWeight, "重量: ");
chinese.message(Message.LabelWeightCapacity, "承重能力: ");
chinese.message(Message.LabelWeightReduction, "减轻重量: ");
chinese.message(Message.LastPlaceYouLeftOff, "醒来你发现自己在你最后倒下的地方...");
chinese.message(Message.LearnedHowToCreate, "你学会了如何制作_0_!");
chinese.message(Message.LeftHand, "左手 (持)");
chinese.message(Message.Legs, "腿");
chinese.message(Message.LikelyFailures, " 建议先制作简单的提高技能熟练度.");
chinese.message(Message.LoadingMods, "载入mod");
chinese.message(Message.LoadingSprites, "载入精灵");
chinese.message(Message.LoadingWorld, "载入世界");
chinese.message(Message.LocalFile, "本地文件");
chinese.message(Message.LocalVersionOfModDetected, "检测到这个mod的本地版本. Workshop版本将不会被载入.");
chinese.message(Message.LoseBonesLayBleaching, "你的骨头变得苍白, 消失在时间里.");
chinese.message(Message.LoseEndIsBeginning, "这个结束只是开始.");
chinese.message(Message.LoseSadlyNoTrace, "令人悲伤的是, 你的踪迹消失无痕.");
chinese.message(Message.LostHealth, "你失去了 _0_ 点生命值.");
chinese.message(Message.LostHunger, "你失去了 _0_ 点饱腹值.");
chinese.message(Message.LostStamina, "你失去了 _0_ 点耐力.");
chinese.message(Message.LostThirst, "你失去了 _0_ 点水分.");
chinese.message(Message.MapNotOfThisArea, "这张地图不是这个区域的.");
chinese.message(Message.MaterialsDestroyedDisassembly, "有些材料在分解的过程中损毁了.");
chinese.message(Message.MaterialsDestroyedDismantle, "有些材料在分解的过程中损毁了.");
chinese.message(Message.MetabolismSlowed, "你的新陈代谢减慢了. 你需要食物和水的分量减少了.");
chinese.message(Message.MilestoneIsHidden, "这个里程碑是隐藏的.");
chinese.message(Message.MilestoneIsInvisible, "这个里程碑是不可见的.");
chinese.message(Message.MissedWith, "你缺少 _0_ 的 _1_!");
chinese.message(Message.MissingRequiredMods, "你缺少或多个必须的mod.");
chinese.message(Message.ModImportedSaveGame, "有个mod导入了存档.");
chinese.message(Message.ModLoadError, "mod载入出错. 有或多个文件损坏.");
chinese.message(Message.ModRequiresItself, "这个mod需要装载.");
chinese.message(Message.ModWithNameAlreadyExists, "有相同名字的mod存在. 尝试更改名字.");
chinese.message(Message.MonsterIdolAttractedCreature, "怪物吸引了另一个生物.");
chinese.message(Message.MouseButton, "M_0_");
chinese.message(Message.MoveAllOfSameQualityToInventory, "把所有相同质量等级的移动到物品栏");
chinese.message(Message.MoveAllOfSameQualityToOpenedContainer, "把所有相同质量等级的移动到打开的容器");
chinese.message(Message.MoveAllToInventory, "移动所有到物品栏");
chinese.message(Message.MoveAllToOpenedContainer, "移动所有到打开的容器");
chinese.message(Message.MoveOverTrapButDoNotSetOff, "你移动了陷阱, 但是没有把它关闭.");
chinese.message(Message.MoveToInventory, "移动到物品栏");
chinese.message(Message.MoveToOpenedContainer, "移动到打开的容器");
chinese.message(Message.MustCastIntoWater, "你需要把这个丢进水里来捕捉.");
chinese.message(Message.Mysteriously, "神秘");
chinese.message(Message.Name, "名字");
chinese.message(Message.NearlyBurnedEquipmentProtectedYou, "你几乎被烧到, 但是你的装备保护你免受烧伤.");
chinese.message(Message.Neck, "脖子");
chinese.message(Message.NeedAShovelToDigTreasure, "你需要一把铲子来挖掘宝藏.");
chinese.message(Message.NeedDeepWaterForRaft, "你需要在深水中使用木筏.");
chinese.message(Message.NeedFishingNetForTreasure, "你需要渔网来获取宝藏.");
chinese.message(Message.NeedToBuildUpLandAround, "你需要在水上建立土地才能把这个放下.");
chinese.message(Message.NeedToEquipToShoot, "你需要装备它才能射击!");
chinese.message(Message.NeedToStartTravelsOutside, "你必须到外面才能开始旅程.");
chinese.message(Message.No, "不");
chinese.message(Message.NoAmmunitionForThatWeapon, "你的物体栏里并没有那个武器的弹药!");
chinese.message(Message.NoBlackPowderToFireWeapon, "你没有火药来开枪.");
chinese.message(Message.NoFireToStokeWith, "没有火源可以点燃_0_!");
chinese.message(Message.NoFishAtLocation, "这个位置没有鱼!");
chinese.message(Message.NoFuelItemsToStartFire, "你没有任何燃料来点火.");
chinese.message(Message.NoInkToDrawMap, "你没有任何墨水来绘制地图!");
chinese.message(Message.NoKindlingToStartFire, "你没有树皮火种用来生火.");
chinese.message(Message.NoLongerFeelPainOBeingfBurned, "你不再感到烧伤的痛苦!");
chinese.message(Message.NoMoreRoomInContainer, "这个容器已经没有足够空间可以放这个物体了.");
chinese.message(Message.NoNeedToStokeFire, "没有必要点火.");
chinese.message(Message.NoRoomToDrop, "这里已经没有空间可以放了!");
chinese.message(Message.NotAvailable, "无效");
chinese.message(Message.NotEnoughFoodToTravel, "你并没有足够的_0_来进行一次旅行!");
chinese.message(Message.NotEnoughPurifiedWaterYet, "这里面没有足够的纯净水可用.");
chinese.message(Message.NotEnoughStrengthToThrow, "你没有足够的体力扔出它!");
chinese.message(Message.NotEnoughTreasureToReturn, "你没有所有财富碎片来回到文明世界.");
chinese.message(Message.NotFacingLockedObject, "你并没有面对锁着的物品.");
chinese.message(Message.NotFacingValidFoodForPreservation, "你并没有面对着有效食物来防腐.");
chinese.message(Message.NotFacingValidItemForReinforcement, "你并没有面对着有效物体来加强.");
chinese.message(Message.NotFacingValidItemForRepair, "你并没有面对着有效物体来修复.");
chinese.message(Message.NotFacingValidItemToTransmogrify, "你并没有面对着有效物体来改变性质.");
chinese.message(Message.NothingHereToCarve, "这里没有任何可以砍的!");
chinese.message(Message.NothingHereToFill, "这里没有任何可以填_0_.");
chinese.message(Message.NothingHereToGardenWith, "这里没有任何可以种_0_!");
chinese.message(Message.NoTinderToStartFire, "你没有任何树叶火种生火.");
chinese.message(Message.NotInRangeOfTreasure, "你不在任何宝藏埋藏的范围里!");
chinese.message(Message.NoWaterInStill, "在这个蒸馏器里没有水.");
chinese.message(Message.NoWhereNearTreasure, "你离财宝还相当地远.");
chinese.message(Message.NumberEight, "8");
chinese.message(Message.NumberFive, "5");
chinese.message(Message.NumberFour, "4");
chinese.message(Message.NumberNine, "9");
chinese.message(Message.NumberOne, "1");
chinese.message(Message.NumberSeven, "7");
chinese.message(Message.NumberSix, "6");
chinese.message(Message.NumberTen, "10");
chinese.message(Message.NumberThree, "3");
chinese.message(Message.NumberTwo, "2");
chinese.message(Message.ObjectIsLocked, "这个物体被锁住了, 你尝试着破坏它来打开.");
chinese.message(Message.Ok, "好的");
chinese.message(Message.OpenDoor, "开门");
chinese.message(Message.OpenFolderFailed, "无法打开文件夹, 请手动选择到文件夹.");
chinese.message(Message.OverEatingLostStamina, "你吃太多了! 你失去了10点体力.");
chinese.message(Message.OverHydratingLostStamina, "你喝了太多水! 你失去了10点体力.");
chinese.message(Message.PaperTurnedToMush, "这张潮湿的纸片从瓶子里拿出来的时候碎掉了.");
chinese.message(Message.PartiallyDecodedMap, "你解码了部分地图.");
chinese.message(Message.PastExperiencesProvideBenefits, "你过去的经历给你的生存带来了好处.");
chinese.message(Message.PenultimateAnd, "和");
chinese.message(Message.PickupItem, "捡起");
chinese.message(Message.Piercing, "刺穿");
chinese.message(Message.Place, "丢弃");
chinese.message(Message.PlacedOnGround, "你把_0_放在地上!");
chinese.message(Message.Plant, "种植");
chinese.message(Message.PlantedInGround, "你把_0_种在地上.");
chinese.message(Message.PlantIsFertile, "这个植物长势良好, 可以往外生长.");
chinese.message(Message.PlantIsNotFertile, "这个植物长势不好, 无法往外生长.");
chinese.message(Message.PlantVeryHealthy, "这个植物长势喜人并且可以往外大量生长.");
chinese.message(Message.Poisoned, "中毒");
chinese.message(Message.PoisonedLostHealth, "你中毒了! 你失去了_0_点生命!");
chinese.message(Message.PoisonWorkedItsCourse, "毒药发作了!");
chinese.message(Message.PouredOutWater, "你把水倒了出来.");
chinese.message(Message.PouredOutWaterOnYourself, "你把水倒在了自己身上.");
chinese.message(Message.PouredWaterIntoStill, "你把水倒进了蒸馏器.");
chinese.message(Message.PreservedFood, "你保存了食物.");
chinese.message(Message.PublishingMod, "发布mod");
chinese.message(Message.PurifiedWaterInStill, "在蒸馏器里有净化的水.");
chinese.message(Message.Quality, "质量");
chinese.message(Message.Recent, "最近");
chinese.message(Message.RefreshingMods, "刷新mod");
chinese.message(Message.Reinforce, "你强化 _0_.");
chinese.message(Message.RemovedBlood, "你除去了血液");
chinese.message(Message.RemoveFromQuickslot, "从快捷栏中删除");
chinese.message(Message.Repair, "修复");
chinese.message(Message.RequiredForDisassembly, "_0_ 在拆分这个物品的时候是必须的!");
chinese.message(Message.RequiredModsMissingWantToContinue, "或多个必须的mod无法找到. 可能发生不可预料的错误. 你确定要继续吗?");
chinese.message(Message.RequiredModsNotLoaded, "或多个必须的mod没有被载入.");
chinese.message(Message.RequiresFacingFireSource, "这个物品要求你面对火源来点燃它.");
chinese.message(Message.RequiresFireToBeLit, "这个蒸馏器需要有火在它下面点燃才能开始净化水.");
chinese.message(Message.RequiresYouToBeFacingTo, "这个物品要求你面对_0_来_1_.");
chinese.message(Message.Rest, "休息");
chinese.message(Message.Rested, "休息");
chinese.message(Message.Resting, "休息中");
chinese.message(Message.RestInterrupted, "你的休息被打断了!");
chinese.message(Message.ReturnedToCivilization, "回到文明世界!");
chinese.message(Message.ReturningToCivilizationSetOffAgain, "把财宝都归还给文明世界之后, 你又开始了旅程...");
chinese.message(Message.ReturnsToLife, "_0_回归生活!");
chinese.message(Message.ReturnToTitleScreenNoSaveInDailyChallenge, "你确定要回到标题界面吗?<br />注意: 在每日挑战模式中你的操作不会被保存.");
chinese.message(Message.ReturnToTitleScreenProgressWillBeSaved, "你确定要回到标题界面吗?<br />注意: 你的操作将会被自动保存.");
chinese.message(Message.RightHand, "右手 (持)");
chinese.message(Message.SailedToCivilization, "在这次游戏里你航行到文明世界了.");
chinese.message(Message.SavingGame, "保存游戏");
chinese.message(Message.Score, "_0_分");
chinese.message(Message.ScrollProvidedNoUsefulInsight, "你精通合成. 这个卷轴不能给你提供有用信息.");
chinese.message(Message.SeaweedFromWater, "你把一团黏糊糊的海藻拖出水面!");
chinese.message(Message.SecondQuarterOfDay, "白天的时间过了将近一半了");
chinese.message(Message.SecondQuarterOfNight, "晚上的时间过了将近一半了.");
chinese.message(Message.SeeGrowing, "你看到_0_生长中的_1_.");
chinese.message(Message.SeemsToHaveDrawnEnergy, "_0_似乎被_1_的能量吸引!");
chinese.message(Message.SetTrapOffButNoDamage, "你设置了陷阱, 但它不会对你造成伤害.");
chinese.message(Message.SetUp, "你设置了_0_.");
chinese.message(Message.ShadowInTheWater, "你看到了水里有个阴影.");
chinese.message(Message.Simple, "简单");
chinese.message(Message.Skill, "技能");
chinese.message(Message.SkillHasRaised, "你的_0_技能熟练度上升至_1_%!");
chinese.message(Message.Slashing, "挥砍");
chinese.message(Message.Sleeping, "睡觉");
chinese.message(Message.SleepInterrupted, "你的睡眠被打断了!");
chinese.message(Message.Slept, "睡着");
chinese.message(Message.Soil, "土壤");
chinese.message(Message.SoilWouldHaveNoEffect, "这种土壤对这种植物不起作用.");
chinese.message(Message.SomethingInTheWayOfCarving, "有东西阻碍了你切开物品!");
chinese.message(Message.SomethingInTheWayOfDigging, "有东西阻碍了你挖洞!");
chinese.message(Message.SomethingInTheWayOfDiggingCarveFirst, "有东西阻碍了你挖洞. 需要被切开.");
chinese.message(Message.SomethingInTheWayOfFishing, "有东西阻碍着你. 你不能在那钓鱼!");
chinese.message(Message.SomethingInTheWayOfGatheringCarveFirst, "有东西阻碍了你收集物品. 需要被切开.");
chinese.message(Message.SomethingInTheWayOfPerforming, "在执行这个动作的时候被某样东西阻碍了.");
chinese.message(Message.SomethingInTheWayOfPlacing, "有东西阻碍了你丢弃物品.");
chinese.message(Message.SomethingInWayOfClosingDoor, "有东西阻碍了你关门!");
chinese.message(Message.SoothedYourBurnInjuries, "你把烧伤治好了!");
chinese.message(Message.Sort, "分类");
chinese.message(Message.SortedByCategory, "_0_ 按类别分类.");
chinese.message(Message.SortedByDecay, "_0_ 按衰败分类.");
chinese.message(Message.SortedByDurability, "_0_ 按耐久分类.");
chinese.message(Message.SortedByGroup, "_0_ 按组别分类.");
chinese.message(Message.SortedByName, "_0_ 按名字分类.");
chinese.message(Message.SortedByQuality, "_0_ 按质量分类.");
chinese.message(Message.SortedByRecent, "_0_ 按时间分类.");
chinese.message(Message.SortedBySkill, "_0_ 按技能分类.");
chinese.message(Message.SortedByWeight, "_0_ 按重量分类.");
chinese.message(Message.StaminaIsFull, "你的体力充沛, 不需要再休息.");
chinese.message(Message.StartedFire, "你点了个火!");
chinese.message(Message.StartTravelInWater, "你需要在海里开始你的旅行.");
chinese.message(Message.StarvingToDeath, "你快因为饥饿而死掉了!");
chinese.message(Message.SteamWorkshop, "Steam Workshop");
chinese.message(Message.SteppingOnHasInjuredYouForDamage, "踩到了 _0_ 让你掉了 _1_ 血!");
chinese.message(Message.StillHasNoWaterToPurify, "这个蒸馏器里没有水!");
chinese.message(Message.StirredUpClawWorm, "你唤醒了地底的爪虫!");
chinese.message(Message.StirredUpCreature, "你唤醒了地底深处的生物!");
chinese.message(Message.StoppedYourBleeding, "你把出血治好了!");
chinese.message(Message.StopUsingRaft, "你停止使用木筏.");
chinese.message(Message.StrengthIncreasing, "你感到自己变强壮了!");
chinese.message(Message.SummonedGuardiansByDiggingTreasure, "你挖宝藏的时候唤醒了宝藏守护者们.");
chinese.message(Message.SunIsRising, "太阳正在升起.");
chinese.message(Message.SunIsSetting, "太阳正在落山.");
chinese.message(Message.SunNotBrightEnoughToStartFire, "太阳不够亮, 无法生火!");
chinese.message(Message.TeleportBlocked, "你的传送目的地被堵住了.");
chinese.message(Message.Teleported, "你传送了.");
chinese.message(Message.ThereIsNoSunToStartFire, "这里没有太阳, 无法生火.");
chinese.message(Message.ThirdQuarterOfDay, "白天的时间已经过去一半.");
chinese.message(Message.ThirdQuarterOfNight, "夜晚的时间已经过去一半.");
chinese.message(Message.Throw, "扔出");
chinese.message(Message.ThrownIntoDepths, "你把_0_丢进了深海里.");
chinese.message(Message.ThrownIntoObstacle, "你把_0_扔烂了.");
chinese.message(Message.TooDamaged, "_0_损坏严重试图_1_.");
chinese.message(Message.TooExhaustedToJump, "你过于疲惫且负担过重, 无法起跳.");
chinese.message(Message.ToolAppearedEffectiveForGathering, "这个工具似乎不能有效地收集这个资源.");
chinese.message(Message.TrampledFire, "你踩到了火, 火熄灭了!");
chinese.message(Message.TrampledIntoGround, "_0_踩踏了地上的_1_.");
chinese.message(Message.TrampleIntoGround, "你踩塌了地上的_0_.");
chinese.message(Message.Trampling, "你踩踏了 _0_.");
chinese.message(Message.Transmogrified, "你已经改变了 _0_.");
chinese.message(Message.TravelAway, "你确定要从这里出发去旅行吗? 你将没办法再回来. 确认带上所有你需要的东西!");
chinese.message(Message.TravelToFarOffLands, "你旅行到遥远的地方...");
chinese.message(Message.TreasureIsBlocked, "你找到宝藏埋藏的地方, 但它是锁着的.");
chinese.message(Message.True, "有效");
chinese.message(Message.UnableToImportSave, "无法载入存档. 该文件可能已损坏或无效.");
chinese.message(Message.UnableToLoadRequiredMods, "未能载入或多个mod.");
chinese.message(Message.UnEquip, "脱下装备");
chinese.message(Message.Unknown, "未知");
chinese.message(Message.UnknownItem, "未知道具");
chinese.message(Message.UnlockedChest, "你打开了木箱子并查看内容物.");
chinese.message(Message.UnpurifiedWaterInStill, "在蒸馏器里有未净化的水.");
chinese.message(Message.UpdatingMod, "更新mod");
chinese.message(Message.URLHasOpenedInWebBrowser, "这个链接已经在你的默认浏览器打开.");
chinese.message(Message.UsedSoilToIncreaseFertility, "你用了土壤来增加植物的肥力.");
chinese.message(Message.UsedToSpeedUpGrowing, "你使用了_0_去加快成长进程.");
chinese.message(Message.UsingBareFistsToFight, "用你的双拳战斗");
chinese.message(Message.UsingBareHandsToGather, "用你的双手收集");
chinese.message(Message.WaitUntilFireCooledToGetWater, "你需要等到火冷却后才能得到纯净的水.");
chinese.message(Message.WalkingDistanceOfTreasure, "你距离宝藏只有步行距离.");
chinese.message(Message.WantToDeleteAllSavedData, "你确定要永久删除所有的存档吗?");
chinese.message(Message.WantToDeleteThisGame, "你确定要删除这个游戏吗?");
chinese.message(Message.WantToPublishThisMod, "你确定要发布这个mod吗?");
chinese.message(Message.WantToPublishUpdateToMod, "你确定要发布这个mod的更新吗?");
chinese.message(Message.WantToUninstallThisMod, "你确定要卸载这个mod吗?");
chinese.message(Message.Water, "水");
chinese.message(Message.WaterDoesNotNeedDesalination, "这种水不需要脱盐!");
chinese.message(Message.WaterIncreaseFertilityOfPlant, "你用了水来增加植物的肥力.");
chinese.message(Message.WaterPutOutFire, "水熄灭了火.");
chinese.message(Message.WaterWouldHaveNoEffect, "水将不会对这种植物起作用.");
chinese.message(Message.Weight, "重量");
chinese.message(Message.WeightCapacity, "重量: _0_ / _1_");
chinese.message(Message.WelcomeToWayward21, `欢迎来到任意岛 beta 2.1.3!<br /><br />请浏览 <a href="https://steamcommunity.com/app/379210/allnews/" target="_blank">Steam Community News</a> 来查看更新.<br /><br /><span class="normal-size">所有mod已经默认禁用.</span>`);
chinese.message(Message.WinFindWayBackToCivilization, "你找到回文明世界的方法并结束了你的旅途.");
chinese.message(Message.WinSailBackWithRiches, "你回去了, 用你的财富过上了美好生活.");
chinese.message(Message.WinTravelledBackToCivilization, "你回到了文明世界, 但是这完结了吗?");
chinese.message(Message.With, "用");
chinese.message(Message.WorkingYourselfIntoExhaustion, "你已经精疲力竭了!");
chinese.message(Message.WorkshopHasBeenOpenedPressOkAfter, "这个Steam Workshop已经在浏览器里打开了.<br />在浏览完Workshop请按OK.");
chinese.message(Message.Yes, "是");
chinese.message(Message.YouAte, "你食用了_0_!");
chinese.message(Message.YouBeginResting, "你开始休息...");
chinese.message(Message.YouCollected, "你收集了_0_!");
chinese.message(Message.YouCrafted, "你_0_ _1_!");
chinese.message(Message.YouDied, "你死于_0_!");
chinese.message(Message.YouDisassembled, "你分解了_0_.");
chinese.message(Message.YouDismantled, "你拆除了_0_.");
chinese.message(Message.YouDrank, "你饮用了_0_!");
chinese.message(Message.YouEquip, "你装备了_0_.");
chinese.message(Message.YouFailedTo, "你尝试_0_ _1_失败了，因为缺乏技能熟练度._2_");
chinese.message(Message.YouFailedToHeal, "你由于缺乏技能熟练度无法治愈_0_.");
chinese.message(Message.YouFire, "你点燃了_0_.");
chinese.message(Message.YouGathered, "你收集了_0_!");
chinese.message(Message.YouHaveKilled, "你杀死了_0_!");
chinese.message(Message.YouOpen, "你打开了_0_.");
chinese.message(Message.YouPickedUp, "你捡起了_0_.");
chinese.message(Message.YouRepair, "你修复了_0_.");
chinese.message(Message.YourFist, "你的拳头");
chinese.message(Message.YouSalvaged, "你打捞了_0_.");
chinese.message(Message.YouSee, "你看到了_0_.");
chinese.message(Message.YouSeparate, "你分开了_0_.");
chinese.message(Message.YouThrew, "你扔出了_0_!");
chinese.message(Message.YouUnequip, "你脱下装备的_0_.");
chinese.message(Message.YouUsed, "你使用了_0_!");

// Items
chinese.item(ItemType.Acorn, "橡果", "一种硬坚果，种植后几天之后长成一棵树苗。", "");
chinese.item(ItemType.Amber, "琥珀", "树脂的化石，可以融化以加强物品。");
chinese.item(ItemType.AnimalFat, "动物脂肪", "动物脂肪，粘糊糊的触感，可作为燃料。");
chinese.item(ItemType.AnimalFatTorch, "动物脂肪火把", "火把；用动物脂肪制成，产生持久的亮光。", "");
chinese.item(ItemType.AnimalSkull, "动物头骨", "空洞的动物头骨，适合制作成临时的头盔。", "");
chinese.item(ItemType.Arrow, "箭", "用弓射出，用箭头和羽毛控制飞行和制成", "");
chinese.item(ItemType.Backpack, "背包", "皮革制成，它非常适合容纳许多物品，减轻整体的重量。", "");
chinese.item(ItemType.Bandage, "绷带", "一块破烂的布，可以止住伤口，防止感染。", "");
chinese.item(ItemType.BarkLeggings, "树皮腿铠", "基础的腿部铠甲，用厚实的树皮制成，用绳子固定。");
chinese.item(ItemType.BarkShield, "树皮盾牌", "临时制作的盾牌，用来抵挡攻击，用树皮和绳子制成。", "");
chinese.item(ItemType.BarkTorch, "树皮火把", "用树皮制作的火把，有天然的油脂来增加火把的使用寿命。", "");
chinese.item(ItemType.BarkTunic, "树皮上衣", "用绳子把树皮绑在一起的胸甲。", "");
chinese.item(ItemType.BerrySeeds, "浆果种子", "它会长成浆果灌木丛，只要有足够的时间和精力。");
chinese.item(ItemType.BigRedBerry, "大红色浆果", "异常大和饱满的红色浆果，充满了营养。", "");
chinese.item(ItemType.BlackPowder, "黑火药", "高度易燃的粉状物，由矿物质组成。");
chinese.item(ItemType.BoatPaddle, "船桨", "船上或战斗中使用的简易船桨。", "");
chinese.item(ItemType.BoiledEgg, "煮鸡蛋", "有水分又美味的煮鸡蛋，美味富含蛋白质。", "");
chinese.item(ItemType.Bone, "骨头", "沉重的动物骨骼，适用于初级的战斗，收集，还可以制作出更多有用的物品。", "");
chinese.item(ItemType.BoneNeedle, "骨针", "骨制的坚硬又锋利的针。", "");
chinese.item(ItemType.BonePole, "骨质棍子", "骨制的光滑的棍子。", "");
chinese.item(ItemType.Bones, "一堆骨头", "从小的脊椎动物得到的，有些破损，相当锋利。");
chinese.item(ItemType.Bow, "弓", "弯腰驼背的木棍，用来发射箭。", "");
chinese.item(ItemType.BowDrill, "取火工具", "先进的取火装置，节省了很大的力气。", "");
chinese.item(ItemType.Branch, "树枝", "用于各种工艺品的制作或取火。", "");
chinese.item(ItemType.BullBoat, "皮质小船", "用来代替步行去往更遥远的土地。", "");
chinese.item(ItemType.CactiSeeds, "仙人掌种子", "这好像是仙人掌的种子，可以种植仙人掌或者直接吃掉。");
chinese.item(ItemType.CactusNeedle, "仙人掌的针", "从仙人掌获取的针，制作更小更复杂的物品时非常有用。", "");
chinese.item(ItemType.CactusSpines, "仙人掌尖刺", "适合手工制成临时使用的针。");
chinese.item(ItemType.Campfire, "营火", "岩石围成的营火。", "");
chinese.item(ItemType.CarbonPowder, "碳粉", "黑色的碳化粉末。");
chinese.item(ItemType.Charcoal, "木炭", "富含碳物质的燃烧物。");
chinese.item(ItemType.CharcoalBandage, "木炭的绷带", "涂上了木炭的布绷带，有天然的防腐和抗凝血功能。", "");
chinese.item(ItemType.ClayBlowpipe, "粘土吹管", "用于吹制各种物品。", "");
chinese.item(ItemType.ClayBrick, "粘土砖", "一种坚硬的用于建筑的物质，如地板和墙壁。", "");
chinese.item(ItemType.ClayBrickFlooring, "粘土砖地板", "由粘土做成的地板，可以装饰或者用于建筑。");
chinese.item(ItemType.ClayBrickWall, "粘土砖墙", "用粘土砌成的墙体。", "");
chinese.item(ItemType.ClayFlakes, "粘土薄片", "由粘土过一段时间后形成。");
chinese.item(ItemType.ClayJug, "粘土罐", "完全硬化的粘土罐子，用于存储水。", "");
chinese.item(ItemType.ClayJugOfDesalinatedWater, "装有淡水的粘土罐", "可以饮用的安全水和粘土罐。", "");
chinese.item(ItemType.ClayJugOfMedicinalWater, "装有药水的粘土罐", "装有药水的粘土罐，用于治疗和缓解某些疾病的同时补充你的水分。", "");
chinese.item(ItemType.ClayJugOfPurifiedFreshWater, "装有纯净水的粘土罐", "装满了新鲜，可以饮用的纯净水，缓解你的口渴。", "");
chinese.item(ItemType.ClayJugOfSeawater, "装有海水的粘土罐", "未经过过滤的海水和粘土罐，现在不宜饮用，但可以被淡化。", "");
chinese.item(ItemType.ClayJugOfUnpurifiedFreshWater, "装有未净化淡水的粘土罐", "新鲜的水，虽然它可以饮用，但是建议进一步纯化。", "");
chinese.item(ItemType.Coal, "煤", "一种黑色的很脆的矿物质，会对接触它的任何物质染色，但可以作为燃料。");
chinese.item(ItemType.CobblestoneFlooring, "鹅卵石地板", "通过把石头放在有组织的位置创造出来的原始地板。");
chinese.item(ItemType.Coconut, "椰子", "纤维状的很重的水果，但挤满了大量的热量密集的椰子肉和牛奶。", "");
chinese.item(ItemType.CompositeBow, "复合弓", "有着熟练技术制作出来的弓，更好的速度和力量。", "");
chinese.item(ItemType.CookedBlindfish, "煮熟的盲鱼", "虽然食物的来源很可疑，但是煮熟之后好像挺可口的。", "");
chinese.item(ItemType.CookedChicken, "煮熟的鸡肉", "精心烹制的鸡肉，一定会很满足。", "");
chinese.item(ItemType.CookedCod, "煮熟的鳕鱼", "煮熟的，准备享受~", "");
chinese.item(ItemType.CookedFishSteak, "煮熟的鱼块", "煮熟的鱼片，美味！", "");
chinese.item(ItemType.CookedMeat, "煮熟的肉", "充分加热了的肉，安全，又美味。");
chinese.item(ItemType.CookedSpider, "煮熟的蜘蛛", "脆脆的蜘蛛，不是最好的味道，但是有少量的白色的肉在里面。", "");
chinese.item(ItemType.CookedTaintedMeat, "煮熟的受污染的肉", "一块变色的肉，虽然煮熟杀死了一些病毒，但仍可能不安全。");
chinese.item(ItemType.CordedSling, "绳吊索", "一块厚厚的绳索，绑了弹槽，用于增加投掷范围。", "");
chinese.item(ItemType.Cork, "软木塞", "一种小的软木塞，用橡胶树的树皮制成，用来盖住装在瓶子或其他容器中的液体。", "");
chinese.item(ItemType.Cotton, "棉花", "一束已经绽开的棉花种子，纺纱线和编织物品的理想材料。");
chinese.item(ItemType.CottonBedroll, "棉睡袋", "一种柔软的睡袋，卷起来便于携带，可以非常舒适地睡眠和休息。", "");
chinese.item(ItemType.CottonFabric, "棉织物", "从棉花上纺出的柔软的布。");
chinese.item(ItemType.CottonSeeds, "棉花种子", "可以种植的棉花种子，也可以用于装饰。");
chinese.item(ItemType.Deadfall, "陷阱", "由大的扁平的岩石和棍子支撑着的陷阱，一旦设置，任何触发它的东西将受到下落的岩石的伤害。", "");
chinese.item(ItemType.DeadSpider, "死蜘蛛", "蜘蛛的尸体，很难下咽，尽管煮熟了，建议你不要想自己吃的是什么东西。", "");
chinese.item(ItemType.DrawnMap, "手绘地图", "一张写满了地理标志和特征的纸，定位模糊的位置。", "");
chinese.item(ItemType.Earthworm, "蚯蚓", "会蠕动的虫子，活的鱼饵，或者自己吃。", "");
chinese.item(ItemType.Ectoplasm, "星魂", "幽灵，轻飘飘的，奇怪的是它会自我控制和会快速挥发。");
chinese.item(ItemType.Egg, "鸡蛋", "诞生于一只鸡，可以直接食用，或者煮成美味。", "");
chinese.item(ItemType.ExplosiveTrap, "爆炸陷阱", "一堆用来掩盖有挥发性爆炸粉末的树叶，踩上它会触发小爆炸。", "");
chinese.item(ItemType.Feather, "羽毛", "鸟类的羽毛。", "");
chinese.item(ItemType.FeatherBedroll, "羽毛睡袋", "一卷柔软的羽毛裹成睡袋，舒适的休息和睡眠。", "");
chinese.item(ItemType.FertileSoil, "肥沃的土壤", "适合植物生长的肥沃的土壤。");
chinese.item(ItemType.FireBladder, "火囊怪", "形状奇特有着呼吸器的生物，摸着很烫，似乎体内有致命的化学反应。", "");
chinese.item(ItemType.FirePlough, "火犁", "一种使用棒和槽的通过摩擦生热的装置。", "");
chinese.item(ItemType.FishingNet, "渔网", "用于捕捉鱼。", "");
chinese.item(ItemType.FishingRod, "钓鱼竿", "光滑的，用于钓鱼。", "");
chinese.item(ItemType.Flask, "烧瓶", "可用于加热海水淡化的玻璃容器，让海水可以饮用。", "");
chinese.item(ItemType.FlintlockPistol, "燧发手枪", "一种远程高伤害的手枪，需要火药和子弹来设计。", "");
chinese.item(ItemType.FlowerPetals, "花瓣", "一朵黄色的花瓣，可以制作药用品，也可以食用。");
chinese.item(ItemType.FlowerSeeds, "花的种子", "可以种植在花卉上的种子。");
chinese.item(ItemType.ForgeAndAnvil, "锻造砧", "用于生产金属武器，装备等工具。", "");
chinese.item(ItemType.Fossil, "化石", "碳化的化石，可能物种早就灭绝了。", "");
chinese.item(ItemType.Furnace, "熔炉", "由石头做成的封闭结构，可以保持高温持久的火。", "");
chinese.item(ItemType.Giblets, "内脏", "一堆熟的动物内脏，很恶心，但很营养。", "");
chinese.item(ItemType.GlassBottle, "玻璃瓶", "一种带有软木塞的透明容器，可以收集水。", "");
chinese.item(ItemType.GlassBottleOfDesalinatedWater, "装有淡水的玻璃瓶", "已去除盐的海水，可以饮用。", "");
chinese.item(ItemType.GlassBottleOfMedicinalWater, "装有药水的玻璃瓶", "可以用于治疗的药水，还能补充一些水分。", "");
chinese.item(ItemType.GlassBottleOfPurifiedFreshWater, "装有纯净的淡水的玻璃瓶", "安全，可饮用的已经被净化的水。", "");
chinese.item(ItemType.GlassBottleOfSeawater, "装有海水的玻璃瓶", "海水技术上是可以饮用的，但是不会缓解你的口渴。", "");
chinese.item(ItemType.GlassBottleOfUnpurifiedFreshWater, "装有未净化淡水的玻璃瓶", "新鲜的水，虽然它可以饮用，但是建议进一步纯化。", "");
chinese.item(ItemType.Glue, "胶水", "可以用来固定、粘合物体的胶水。");
chinese.item(ItemType.GoldCoins, "金币", "闪亮的金币，来自失落的文明。");
chinese.item(ItemType.GoldenChalice, "黄金圣杯", "大的，华丽的酒杯。", "");
chinese.item(ItemType.GoldenKey, "金钥匙", "由黄金锻造的钥匙。", "");
chinese.item(ItemType.GoldenRing, "金戒指", "一枚金色的戒指，最可能是用来彰显财富的象征。", "");
chinese.item(ItemType.GoldenSword, "黄金剑", "华丽的但柔软的剑，不适合战斗因为它很软。", "");
chinese.item(ItemType.GrassBlades, "草的叶片", "又长，摸着又锋利，是完美的制作绳索和弦之类的材料。");
chinese.item(ItemType.GrassSeeds, "草的种子", "可以种植草。");
chinese.item(ItemType.GreenSand, "粘土沙", "一种用粘土制成的可塑性沙子，可以用来做金属铸件的模具。");
chinese.item(ItemType.Grindstone, "磨刀石", "一种用于打磨，锐化，修补其他物品的石头。", "");
chinese.item(ItemType.Hammock, "吊床", "舒适的睡觉的地方，但是不太牢固。", "");
chinese.item(ItemType.HandDrill, "手用生火器", "一种使用木棍和另一块木头制成的生火器，摩擦生火，", "");
chinese.item(ItemType.Inkstick, "墨水块", "用于绘画和书写的墨水砖块。", "");
chinese.item(ItemType.IronArrow, "铁箭", "一支高质量的箭。", "");
chinese.item(ItemType.IronArrowhead, "铁箭头", "由熟练的锻造技术锻造出来的铁箭头，用来制作箭，如果你喜欢可以用于雕刻。", "");
chinese.item(ItemType.IronBoots, "铁靴", "沉重的鞋子，避免你的脚收到伤害。");
chinese.item(ItemType.IronBreastplate, "铁胸甲", "耐久很高，人受到严重殴打之前穿上非常好。", "");
chinese.item(ItemType.IronBullet, "铁质子弹", "一颗结实的子弹，用作武器子弹。", "");
chinese.item(ItemType.IronChest, "铁箱子", "大铁箱子，里面的食物会以较慢的速度腐烂。", "");
chinese.item(ItemType.IronDoubleAxe, "铁质双刃斧", "锻造出来的斧头，理想的战斗和采集的装备。", "");
chinese.item(ItemType.IronGauntlets, "铁质手套", "铁手套是非常耐用而且可以很好保护你的，也有尽可能好的灵活性。");
chinese.item(ItemType.IronGorget, "铁质护喉", "可以保护你的喉咙，颈部。", "");
chinese.item(ItemType.IronGreaves, "铁质护胫甲", "铁质护腿，绑在腿上很不错。");
chinese.item(ItemType.IronHammer, "铁质锤子", "完美的修复和锻造工具。", "");
chinese.item(ItemType.IronHelmet, "铁质头盔", "可以承受大的打击。", "");
chinese.item(ItemType.IronIngot, "铁淀", "一种可以制作很多物品的矿石。", "");
chinese.item(ItemType.IronLockPick, "铁质开锁工具", "足够耐用的撬锁的工具。", "");
chinese.item(ItemType.IronOre, "铁矿石", "未加工的原料铁矿石。");
chinese.item(ItemType.IronPickaxe, "铁质十字镐", "强大的挖掘工具。", "");
chinese.item(ItemType.IronShield, "铁质盾牌", "强大的护盾，用于抵挡子弹和攻击。", "");
chinese.item(ItemType.IronShovel, "铁质铲子", "沉重的挖掘工具，坚硬到可以挖掘砾石土。", "");
chinese.item(ItemType.IronSpear, "铁质矛", "强大的锋利武器。", "");
chinese.item(ItemType.IronSword, "铁剑", "强大的锋利的削铁如泥的武器。", "");
chinese.item(ItemType.IronTongs, "铁火钳", "耐用的铁质火钳可以帮助你夹住高温的物品不会被烫伤。");
chinese.item(ItemType.Kiln, "窑炉", "类似于熔炉，但是砂岩制作的，有着适当的热量分布，可以制作玻璃和粘土等。", "");
chinese.item(ItemType.Kindling, "树皮火种", "一堆小树枝和树叶，取火的必备品。");
chinese.item(ItemType.LargeRock, "巨大的岩石", "巨大的岩石，可以制作很多东西。", "");
chinese.item(ItemType.LeafBedroll, "叶子铺盖", "临时的床，用于睡觉和休息。", "");
chinese.item(ItemType.LeatherBelt, "皮带", "动物的皮切割缝合，绑在腰上。", "");
chinese.item(ItemType.LeatherBoots, "皮革靴", "坚韧的靴子，用动物的皮制成。");
chinese.item(ItemType.LeatherCap, "皮革帽子", "屁股做的帽子，双层结构更好的保护。", "");
chinese.item(ItemType.LeatherGloves, "皮革手套", "保护双手，动物的皮制成。");
chinese.item(ItemType.LeatherGorget, "皮革护喉", "保护你的颈部，非常棒。", "");
chinese.item(ItemType.LeatherHide, "皮革", "崭新的皮革，来自于某只可怜的动物。", "");
chinese.item(ItemType.LeatherPants, "皮革裤", "提供一些基本的腿部保护。");
chinese.item(ItemType.LeatherQuiver, "皮革箭袋", "皮革制作的背在背上的袋子，主要容纳箭羽，但是其他物品也可以容纳。", "");
chinese.item(ItemType.LeatherSling, "皮革绳索", "皮革制成。可以让弹丸被抛出的时候增加速度。", "");
chinese.item(ItemType.LeatherTunic, "皮革外套", "为身体提供保护的一种皮革服装。", "");
chinese.item(ItemType.Leaves, "叶子", "少量的树叶作为肥料或生火。");
chinese.item(ItemType.Lens, "透镜", "它允许将阳光聚焦到一个点，为生火创造足够的热量。", "");
chinese.item(ItemType.Limestone, "石灰岩", "一种可以被研磨成粉末的富含矿物的岩石。可用于金属和玻璃的生产。");
chinese.item(ItemType.LimestonePowder, "石灰岩粉", "一种用于玻璃和金属生产的白色的矿物粉末。");
chinese.item(ItemType.LitAnimalFatTorch, "燃烧的动物脂肪火把", "明亮的，燃烧中的，持久的，有愉快的气味的火把，用动物脂肪制成。", "");
chinese.item(ItemType.LitBarkTorch, "燃烧的树皮火把", "为你的周围提供亮光，也可以用来点着其他物品。", "");
chinese.item(ItemType.LitPoleTorch, "燃烧的木杆火把", "被点燃的木头柱子。不适合在黑暗中的长途旅行。", "");
chinese.item(ItemType.LockPick, "开锁器", "一个简易的针尖头，足以开一次或者两次锁。", "");
chinese.item(ItemType.Log, "原木", "结实的木头，用于制作或是火的燃料。", "");
chinese.item(ItemType.LongBow, "长弓", "几乎和人一样高的弓，可以射超大的距离。", "");
chinese.item(ItemType.MagicalEssence, "魔法精华", "奇怪的，透明的，有机的，轻盈的东西。这个神奇的物质可以用来在物品上附上魔法属性。");
chinese.item(ItemType.MeltedAmber, "熔化的琥珀", "用于放在某个物品上硬化成型。");
chinese.item(ItemType.MessageInABottle, "带信的瓶子", "一个旧的瓶子，里面装着一个不明物体。", "");
chinese.item(ItemType.MonsterIdol, "怪物雕像", "大量的动物器官形成的某种雕像。它闻起来很难闻，发出一种奇怪的嗡嗡声，在吸引动物。", "");
chinese.item(ItemType.MortarAndPestle, "研磨器", "用于粉碎，由光滑的石头制成。", "");
chinese.item(ItemType.Niter, "硝石", "一种天然矿物，可作为防腐剂或其他化学用途。");
chinese.item(ItemType.Nopal, "仙人掌", "有刺的仙人掌的果实，充满了清凉的液体和营养。");
chinese.item(ItemType.Offal, "内脏", "一个不幸的动物的一堆器官、组织和其他有点恶心的部分。");
chinese.item(ItemType.OldInstructionalScroll, "古老的教学纸卷", "一张破破烂烂的纸上写了一些大致的说明和图表。", "");
chinese.item(ItemType.OrnateCape, "华丽的披肩", "金红色的斗篷，系在脖子后面。作为地位的象征。", "");
chinese.item(ItemType.OrnateWoodenChest, "华丽的木箱子", "有一些镶嵌在木头上的装饰的木箱子。", "");
chinese.item(ItemType.PalmLeaf, "棕榈叶", "从棕榈树上取下的一片叶子。叶子纤维是完美的绳索材料。", "");
chinese.item(ItemType.PaperMold, "纸模具", "一种用于造纸的模具，可以压制成扁平的，可用的纸。", "");
chinese.item(ItemType.PaperSheet, "纸张", "一大张纸，适合于油墨画。", "");
chinese.item(ItemType.Peat, "泥煤", "一种海绵状的东西，非常适合用于燃烧燃料和施肥。");
chinese.item(ItemType.PeatBandage, "泥煤绷带", "织物绷带结合泥煤作为一种有效的防腐剂。", "");
chinese.item(ItemType.Pemmican, "干肉饼", "有很长的保质期，这是救命的食物，把它与动物脂肪一起食用。");
chinese.item(ItemType.PileOfAsh, "灰烬", "燃烧物的粉末物。", "");
chinese.item(ItemType.PileOfCompost, "肥料", "腐烂的有机物质和土壤的混合，充满化学成分和加速植物生长。", "");
chinese.item(ItemType.PileOfGravel, "砾石", "一大堆潮湿的石头和沙子。", "");
chinese.item(ItemType.PileOfSand, "沙子", "一大堆潮湿的沙子，可用于制作玻璃。", "");
chinese.item(ItemType.PileOfSnow, "雪", "在绝望的时候的水源。", "");
chinese.item(ItemType.Pineapple, "菠萝", "一个多汁的成熟的菠萝，含有维生素和解渴的属性。", "");
chinese.item(ItemType.PineappleSeeds, "菠萝种子", "可以种植菠萝的棕色种子。");
chinese.item(ItemType.PlantRoots, "植物的根部", "一团混乱的根");
chinese.item(ItemType.PoisonIvyLeaves, "有毒的常春藤叶", "触摸会造成伤害，它不属于你。");
chinese.item(ItemType.PoisonIvySeeds, "毒藤种子", "明亮的绿色的，柔软的种子，用来种植毒常春藤。");
chinese.item(ItemType.PreparedPemmican, "制备的干肉饼", "一种干燥的肉，最大的热量含量。");
chinese.item(ItemType.Raft, "木筏", "一只小的简单的船；替代你游泳，穿越大片的水。", "");
chinese.item(ItemType.RawBlindfish, "生的盲鱼", "没有眼睛的奇怪的鱼。触感非常黏。", "");
chinese.item(ItemType.RawChicken, "生鸡肉", "小的，丰满的，有羽毛的鸡的胴体，可以烹饪。", "");
chinese.item(ItemType.RawClay, "粘土", "柔软的，成型的粘土。适用于建筑材料，工具制造，以及更多物品。");
chinese.item(ItemType.RawClayBlowpipe, "粘土吹管", "一种用于吹制玻璃的吹管。无法使用直到被烧制。", "");
chinese.item(ItemType.RawClayBrick, "粘土砖", "一块软的原始粘土塑造成的长方形。准备在一个窑炉内被烧制。", "");
chinese.item(ItemType.RawClayJug, "粘土罐", "粘土塑造的罐子。需要一个软木和一个窑炉来烧制硬化。", "");
chinese.item(ItemType.RawCod, "生鳕鱼", "摸起来黏糊糊的，但是健康和美味的食物。可以做一顿更好的饭。", "");
chinese.item(ItemType.RawFishSteak, "生鱼排", "一条生的鱼，好吃是好吃，但需要煮熟。", "");
chinese.item(ItemType.RawMeat, "生肉", "一块肉，烹饪前不建议食用。");
chinese.item(ItemType.RawTaintedMeat, "受污染的生肉", "一块带难闻气味的肉，可能有病或有寄生虫感染。食用可能是致命的。");
chinese.item(ItemType.RedBerries, "红浆果", "成熟的浆果，从树上或是灌木摘下。");
chinese.item(ItemType.RefinedSand, "精砂", "一种很细的沙子，在制作玻璃时很有用。");
chinese.item(ItemType.RollOfRedCarpet, "卷着的红地毯", "卷起来的红地毯，适合做一个舒适的生活空间或欢迎重要的客人", "");
chinese.item(ItemType.Rope, "绳子", "用于重型物体的捆绑，", "");
chinese.item(ItemType.RottenMeat, "腐烂的肉", "刺鼻的腐烂的动物组织。你不想吃这个，但可以用在施肥上。");
chinese.item(ItemType.RottingVegetation, "腐烂的植物", "臭的有机植物物质，现在可用作施肥。除非你想冒险吃它。");
chinese.item(ItemType.Sail, "风帆", "一块大的织物，织在一起被连接到桅杆上。用于帆船。", "");
chinese.item(ItemType.Sailboat, "帆船", "大的单人艇。用于穿越大片的水和回到文明。", "");
chinese.item(ItemType.Saltpeter, "硝石", "一种地面矿物，用作天然食品防腐剂。如果与其他矿物结合，它是可燃的。");
chinese.item(ItemType.SandCastFlask, "沙制模具", "一种将金属铸造成任何形状的模具，用绿色的沙子制成。", "");
chinese.item(ItemType.Sandstone, "砂岩", "一种柔软、可锻造的岩石，用于建筑和工具制造。");
chinese.item(ItemType.SandstoneFlooring, "砂岩地板", "放置在一个格子中用作地板。");
chinese.item(ItemType.SandstoneWall, "砂岩墙", "由人工建造的墙。", "");
chinese.item(ItemType.Sapling, "树苗", "年轻的树，适合移植它。", "");
chinese.item(ItemType.Seaweed, "海藻", "一种海洋植物。可作为绝望时的救命绳索或吃掉它。");
chinese.item(ItemType.Shale, "页岩", "脆而锋利的雕刻工具。");
chinese.item(ItemType.SharpenedBone, "锋利的骨头", "一个锋利的骨头，用于雕刻其他物体。", "");
chinese.item(ItemType.SharpGlass, "尖锐的玻璃", "半透明的碎片，融化后形成沙子。");
chinese.item(ItemType.SharpRock, "锋利的岩石", "锋利的岩石，用于工具制作，雕刻。", "");
chinese.item(ItemType.SheetOfGlass, "玻璃片", "一块玻璃。非常实用，可以制作许多光学工具和其他简单的设备。", "");
chinese.item(ItemType.ShortBow, "短弓", "一个为近距离强力射击而设计的弓。", "");
chinese.item(ItemType.Sinew, "肌腱", "强壮且灵活的动物组织。常用的制弓材料或简单的绳索。");
chinese.item(ItemType.SkeletalMageWand, "骷髅法师的魔杖", "一个神秘的扭曲闪烁的红色宝石魔杖。", "");
chinese.item(ItemType.Skullcap, "便帽", "一具动物的头骨，用作临时头盔。", "");
chinese.item(ItemType.SlimeGelatin, "粘液凝胶", "可以用来保存食物或熔化它并用作胶水。");
chinese.item(ItemType.SmallBag, "小包包", "用来装一些物品，皮革袋，携带在你的腰部，减少负重。", "");
chinese.item(ItemType.SmoothRock, "光滑的岩石", "圆形，光滑的岩石，可以制作许多工艺品。", "");
chinese.item(ItemType.Snare, "陷阱", "设计的用处在于诱捕动物。", "");
chinese.item(ItemType.Soil, "泥土", "一堆潮湿的泥土。泥土的气息弥漫在你的鼻孔里。");
chinese.item(ItemType.SolarStill, "太阳能蒸馏器", "收集冷凝的水并过滤，使淡化水排到容器里。", "");
chinese.item(ItemType.SpiderEggs, "蜘蛛的卵", "柔柔的触摸感。这些卵里有蜘蛛的生命。");
chinese.item(ItemType.SpiderSilk, "蜘蛛丝", "由蜘蛛产生的一种精巧而坚固的丝缕。可以作为绳索。");
chinese.item(ItemType.SpottedRedMushroom, "斑点红色蘑菇", "奇怪的臭蘑菇。", "");
chinese.item(ItemType.Spyglass, "望远镜", "简易的，短距离的望远镜，它可以被用来看稍微更远的距离的东西。", "");
chinese.item(ItemType.StoneArrowhead, "石质箭头", "从石头制作，并用于制作箭。也可以作为一个雕刻工具。", "");
chinese.item(ItemType.StoneAxe, "石质斧", "一种两用工具既尖锐又钝。可以用来砍木头或矿石。", "");
chinese.item(ItemType.StoneBullet, "石质子弹", "非常基础的石弹丸。光滑和类似球形的形状。", "");
chinese.item(ItemType.StoneHammer, "石质锤子", "一个简陋的石锤，用于收集和修理。", "");
chinese.item(ItemType.StoneKnife, "石质刀子", "一块锋利的石头，雕刻成一个刀片，用一个手柄支撑。可作为武器、收集工具或雕刻。", "");
chinese.item(ItemType.Stones, "石头", "大量的小岩石。可用于投掷或制造。");
chinese.item(ItemType.StoneShovel, "石质铲", "一种由石头制成的挖掘工具，用来收集地面上的材料或水。", "");
chinese.item(ItemType.StoneSpear, "石质矛", "一种用石头制成的狩猎武器，适合作为投掷武器。", "");
chinese.item(ItemType.StoneWall, "石头墙", "石头和岩石形成的一个垂直的墙结构，以抵挡敌人。", "");
chinese.item(ItemType.StoneWaterStill, "石水蒸馏器", "掏空的岩石与石头盖。它用于沸腾淡化水，然后收集蒸汽进一个单独的容器。", "");
chinese.item(ItemType.String, "绳索", "机织物，主要用于捆绑物品。");
chinese.item(ItemType.StrippedBark, "细丝状的树皮", "强大的，纤维状的，用于制造绳索.");
chinese.item(ItemType.Sundial, "日晷", "类似文明世界的手表，用太阳或月亮的位置显示白天或夜晚的大致时间。", "");
chinese.item(ItemType.Suture, "缝合针", "一个带有细绳和尖针的工具，用来缝闭裂开的伤口。", "");
chinese.item(ItemType.TailFeathers, "尾羽", "蓬松的白色的羽毛，从动物的背部获取。");
chinese.item(ItemType.Talc, "滑石矿", "有用的粉末状物品。");
chinese.item(ItemType.TalcumPowder, "滑石粉", "铸造先进金属所需的材料。");
chinese.item(ItemType.TallGrassSeeds, "高高草得种子", "可以种植长长的草。");
chinese.item(ItemType.TannedLeather, "鞣制皮革", "耐用的，经过处理的一块皮革。用于制作盔甲和其他工具。");
chinese.item(ItemType.Tannin, "鞣酸", "天然处理剂。适用于制造鞣制皮革。");
chinese.item(ItemType.TatteredMap, "破碎的地图", "有一些涂鸦，第一眼要看懂感觉有点难。", "");
chinese.item(ItemType.TatteredPants, "破烂的裤子", "已经被磨损成短裤的裤子。");
chinese.item(ItemType.TatteredShirt, "破烂的衬衫", "一件精美的服装，但是现在破烂不堪。", "");
chinese.item(ItemType.Thistles, "蓟草", "开花的植物。充满了苦涩但有营养的汁。");
chinese.item(ItemType.ThistleSeeds, "蓟草的种子", "小而硬的种子，生长成蓟蓟草。");
chinese.item(ItemType.Tinder, "树叶火种", "用于点燃生火。");
chinese.item(ItemType.Tourniquet, "止血带", "绳子缠绕在一起。缠绕在流血的伤口上以阻止血液的丢失。", "");
chinese.item(ItemType.TreeBark, "树皮", "一种坚韧的、浓密的树皮，从树上获取。");
chinese.item(ItemType.TreeFungus, "树上的真菌", "一种半硬的真菌，可能可以食用。");
chinese.item(ItemType.Twigs, "一堆树枝", "一小堆树枝。");
chinese.item(ItemType.VenomGland, "毒腺", "一条蛇的毒液腺，仍有一些毒液在上面。", "");
chinese.item(ItemType.Vine, "藤蔓", "长长的藤蔓，适合制作绳索。", "");
chinese.item(ItemType.VineSeeds, "葡萄籽", "种植葡萄树。如果绝望的话你也可以使用它们，但它们显然不包含任何营养。");
chinese.item(ItemType.VineWhip, "藤蔓鞭", "一个简单的武器，简单地用藤蔓缠绕在一起。", "");
chinese.item(ItemType.Waterskin, "水袋", "一种可携带的水容器，由缝合皮革制成。", "");
chinese.item(ItemType.WaterskinOfDesalinatedWater, "装有淡化水的水袋", "充满新鲜的淡化水。", "");
chinese.item(ItemType.WaterskinOfMedicinalWater, "装有药水的水袋", "可以用于治愈某些病痛的药水。", "");
chinese.item(ItemType.WaterskinOfPurifiedFreshWater, "装有纯净水的水袋", "可以饮用得很快乐的水。", "");
chinese.item(ItemType.WaterskinOfSeawater, "装有海水的水袋", "充满海水的水袋，不适合饮用，没有淡化。", "");
chinese.item(ItemType.WaterskinOfUnpurifiedFreshWater, "装有未净化的淡水的水袋", "未纯化的和可能有害的水。建议您在净化后饮用。", "");
chinese.item(ItemType.WhiteMushrooms, "白蘑菇", "他们似乎是安全的食物。");
chinese.item(ItemType.WildOnion, "野生洋葱", "一种有强烈气味和味道的植物，充满了营养和维生素。", "");
chinese.item(ItemType.WoodenArrow, "木质箭", "从弓上发射的临时箭羽。用羽毛控制飞行。", "");
chinese.item(ItemType.WoodenChest, "木箱子", "放置在地面上的一个大的木制容器，可以容纳许多物品。食物会在它里面腐烂得更慢。", "");
chinese.item(ItemType.WoodenDoor, "木门", "可以打开和关闭的木头门。", "");
chinese.item(ItemType.WoodenFence, "木栅栏", "一段木制围栏。", "");
chinese.item(ItemType.WoodenFlooring, "木质地板", "这只是一个木头做的地板。");
chinese.item(ItemType.WoodenGate, "木制闸门", "可以打开和关闭的闸门。", "");
chinese.item(ItemType.WoodenPole, "木杆", "一块很长的木头，从树枝或木头上切割而成的一根光滑的木头。", "");
chinese.item(ItemType.WoodenSpear, "木矛", "一个临时的，易于制造的狩猎武器。一个理想的远程武器。", "");
chinese.item(ItemType.WoodenTongs, "木钳子", "一副简单的木夹子，用来夹起烫的物体不损伤自己。");
chinese.item(ItemType.WoodenWall, "木头墙", "坚固的墙体，可以保护你的墙。", "");
chinese.item(ItemType.WovenFabric, "编织织物", "一种纤维组织织成的织物。");
chinese.item(ItemType.WroughtIron, "铸铁", "严重氧化和很多杂质的铁，用于制作工具，锻造武器和盔甲。");
chinese.item(ItemType.WroughtIronArrow, "铁质箭", "有一个铁箭头的箭。", "");
chinese.item(ItemType.WroughtIronArrowhead, "铁箭头", "这个箭头是用来制作箭，它也可以用于雕刻。", "");
chinese.item(ItemType.WroughtIronBoots, "铁靴", "非常坚固的铁鞋。重型的，专门为保护大腿和小腿。");
chinese.item(ItemType.WroughtIronBreastPlate, "铁胸甲", "一个大铁胸甲，穿在身体上。", "");
chinese.item(ItemType.WroughtIronBullet, "铁质子弹", "作为弹弓或枪支的弹药。", "");
chinese.item(ItemType.WroughtIronChest, "铁箱子", "一个宽敞的铁制作的箱子，可以存储许多物品。食物会减缓腐坏速度。", "");
chinese.item(ItemType.WroughtIronDoubleAxe, "铁质双刃斧", "双斧刃可以提供足够的挥砍伤害为战斗和采集。", "");
chinese.item(ItemType.WroughtIronGauntlets, "铁质护手", "可以很好的保护你的手臂和手腕。");
chinese.item(ItemType.WroughtIronGorget, "铁质护喉", "保护你的喉咙以免遭受攻击。", "");
chinese.item(ItemType.WroughtIronGreaves, "铁质护胫", "绑在腿上以减少伤害。");
chinese.item(ItemType.WroughtIronHammer, "铁质锤子", "用于修复和收集。", "");
chinese.item(ItemType.WroughtIronHelmet, "铁质头盔", "防御对你的头的攻击。", "");
chinese.item(ItemType.WroughtIronLockPick, "铁质开锁器", "用于解锁锁定装置。", "");
chinese.item(ItemType.WroughtIronPickaxe, "铁质镐子", "双头采矿工具。一头沉重，另一头加钉，以轻松地穿过岩石。", "");
chinese.item(ItemType.WroughtIronShield, "铁质盾牌", "一个坚固的铁盾牌，由弯曲的金属制成。", "");
chinese.item(ItemType.WroughtIronShovel, "铁质铲子", "有角度的尖头，用于挖掘和收集水。", "");
chinese.item(ItemType.WroughtIronSpear, "铁矛", "在战斗中使用。", "");
chinese.item(ItemType.WroughtIronSword, "铁剑", "长的，尖锐的刀片安装在一个坚实的剑柄上，一个好的，有力的武器。", "");
chinese.item(ItemType.WroughtIronTongs, "铁钳", "一把钳子，用于夹起烫的物品不受伤。");

// Groups
chinese.itemGroup(ItemTypeGroup.Arrow, "箭头", "");
chinese.itemGroup(ItemTypeGroup.Bedding, "卧具", "", "");
chinese.itemGroup(ItemTypeGroup.Bone, "骨头", "");
chinese.itemGroup(ItemTypeGroup.Bullet, "子弹", "");
chinese.itemGroup(ItemTypeGroup.Carbon, "碳类", "", "物品");
chinese.itemGroup(ItemTypeGroup.ClayJugOfPotableWater, "饮用水粘土罐", "");
chinese.itemGroup(ItemTypeGroup.Compost, "肥料", "", "");
chinese.itemGroup(ItemTypeGroup.Container, "容器", "");
chinese.itemGroup(ItemTypeGroup.ContainerOfDesalinatedWater, "淡水容器", "");
chinese.itemGroup(ItemTypeGroup.ContainerOfMedicinalWater, "药水容器", "");
chinese.itemGroup(ItemTypeGroup.ContainerOfPurifiedFreshWater, "纯净水容器", "");
chinese.itemGroup(ItemTypeGroup.ContainerOfSeawater, "海水容器", "");
chinese.itemGroup(ItemTypeGroup.ContainerOfUnpurifiedFreshWater, "未净化淡水容器", "");
chinese.itemGroup(ItemTypeGroup.CookedMeat, "煮熟的肉", "", "");
chinese.itemGroup(ItemTypeGroup.Cordage, "绳索", "", "");
chinese.itemGroup(ItemTypeGroup.Equipment, "装备", "", "");
chinese.itemGroup(ItemTypeGroup.Fabric, "织物", "", "");
chinese.itemGroup(ItemTypeGroup.Firemaking, "取火", "", "物品");
chinese.itemGroup(ItemTypeGroup.Food, "食物", "", "");
chinese.itemGroup(ItemTypeGroup.Fuel, "燃料", "", "");
chinese.itemGroup(ItemTypeGroup.Gardening, "园艺", "", "物品");
chinese.itemGroup(ItemTypeGroup.GlassBottleOfPotableWater, "饮用水玻璃瓶", "");
chinese.itemGroup(ItemTypeGroup.Hammer, "铁锤", "");
chinese.itemGroup(ItemTypeGroup.Health, "健康", "", "物品");
chinese.itemGroup(ItemTypeGroup.Heating, "加热", "", "物品");
chinese.itemGroup(ItemTypeGroup.Housing, "住房", "", "");
chinese.itemGroup(ItemTypeGroup.Insect, "昆虫", "");
chinese.itemGroup(ItemTypeGroup.LightSource, "光源", "");
chinese.itemGroup(ItemTypeGroup.Meat, "肉类", "", "");
chinese.itemGroup(ItemTypeGroup.Medicinal, "医药", "", "物品");
chinese.itemGroup(ItemTypeGroup.Needle, "针", "");
chinese.itemGroup(ItemTypeGroup.Other, "其他", "", "");
chinese.itemGroup(ItemTypeGroup.Pole, "木杆", "");
chinese.itemGroup(ItemTypeGroup.Powder, "粉末", "");
chinese.itemGroup(ItemTypeGroup.Preservative, "防腐剂", "");
chinese.itemGroup(ItemTypeGroup.Pulp, "果肉", "", "");
chinese.itemGroup(ItemTypeGroup.RawMeat, "生肉", "", "");
chinese.itemGroup(ItemTypeGroup.Reinforce, "加固", "", "物品");
chinese.itemGroup(ItemTypeGroup.Repair, "修理", "", "物品");
chinese.itemGroup(ItemTypeGroup.Rock, "岩石", "");
chinese.itemGroup(ItemTypeGroup.Sharpened, "锋利", "", "物品");
chinese.itemGroup(ItemTypeGroup.SharpenedRock, "锋利岩石", "");
chinese.itemGroup(ItemTypeGroup.Skewer, "木杆", "");
chinese.itemGroup(ItemTypeGroup.Storage, "贮藏", "", "物品");
chinese.itemGroup(ItemTypeGroup.Tongs, "钳子", "");
chinese.itemGroup(ItemTypeGroup.Tool, "工具", "");
chinese.itemGroup(ItemTypeGroup.Transmogrify, "变形", "", "物品");
chinese.itemGroup(ItemTypeGroup.Trap, "陷阱", "");
chinese.itemGroup(ItemTypeGroup.Travel, "旅行", "", "物品");
chinese.itemGroup(ItemTypeGroup.Treasure, "宝物", "");
chinese.itemGroup(ItemTypeGroup.Water, "水类", "", "");
chinese.itemGroup(ItemTypeGroup.WaterskinOfPotableWater, "饮用水水袋", "");
chinese.itemGroup(ItemTypeGroup.Weapon, "武器", "");

// Doodads
chinese.doodad(DoodadType.Acid, "酸性");
chinese.doodad(DoodadType.BarePalmTree, "赤裸的棕榄树", "");
chinese.doodad(DoodadType.BareTree, "赤裸的树", "");
chinese.doodad(DoodadType.BerryBush, "浆果灌木", "");
chinese.doodad(DoodadType.Cacti, "仙人掌");
chinese.doodad(DoodadType.Campfire, "篝火", "");
chinese.doodad(DoodadType.CaveEntrance, "洞穴入口", "");
chinese.doodad(DoodadType.ClayBrickWall, "粘土砖墙", "");
chinese.doodad(DoodadType.Cotton, "棉");
chinese.doodad(DoodadType.DeadBush, "枯萎的灌木", "");
chinese.doodad(DoodadType.ForgeAndAnvil, "锻造砧", "");
chinese.doodad(DoodadType.Furnace, "炉子", "");
chinese.doodad(DoodadType.GrowingGrass, "生长中的草");
chinese.doodad(DoodadType.GrowingMushroom, "生长中的蘑菇", "");
chinese.doodad(DoodadType.GrowingPlant, "生长中的植物", "");
chinese.doodad(DoodadType.IronChest, "铁箱子", "");
chinese.doodad(DoodadType.Kiln, "窑炉", "");
chinese.doodad(DoodadType.LitCampfire, "燃烧中的篝火", "");
chinese.doodad(DoodadType.LitForgeAndAnvil, "燃烧中的锻造砧", "");
chinese.doodad(DoodadType.LitFurnace, "燃烧中的炉子", "");
chinese.doodad(DoodadType.LitKiln, "燃烧中的窑炉", "");
chinese.doodad(DoodadType.LitStoneWaterStill, "燃烧中的石水", "");
chinese.doodad(DoodadType.LitTorchStand, "燃烧中的火炬台", "");
chinese.doodad(DoodadType.LockedWoodenChest, "上锁的木箱", "");
chinese.doodad(DoodadType.MonsterIdol, "怪物雕像", "");
chinese.doodad(DoodadType.OrnateWoodenChest, "华丽的木质箱", "");
chinese.doodad(DoodadType.PalmTree, "棕榄树", "");
chinese.doodad(DoodadType.PalmTreeWithCoconuts, "椰子棕榄树", "");
chinese.doodad(DoodadType.PileOfRocks, "岩石堆", "");
chinese.doodad(DoodadType.PineapplePlant, "菠萝", "");
chinese.doodad(DoodadType.PoisonIvy, "毒藤");
chinese.doodad(DoodadType.SandstoneWall, "砂岩墙", "");
chinese.doodad(DoodadType.Sapling, "树苗", "");
chinese.doodad(DoodadType.Seaweed, "海藻");
chinese.doodad(DoodadType.SetDeadfall, "设置好的陷阱", "");
chinese.doodad(DoodadType.SetExplosiveTrap, "设置好的爆炸陷阱", "");
chinese.doodad(DoodadType.SetHobgoblinSnare, "设置好的怪物陷阱", "");
chinese.doodad(DoodadType.SetSnare, "设置好的陷阱", "");
chinese.doodad(DoodadType.SolarStill, "太阳蒸馏器", "");
chinese.doodad(DoodadType.SpottedRedMushroom, "带斑点的红色蘑菇", "");
chinese.doodad(DoodadType.StoneWall, "岩石墙", "");
chinese.doodad(DoodadType.StoneWaterStill, "石水蒸馏器", "");
chinese.doodad(DoodadType.TallGrass, "高高的草");
chinese.doodad(DoodadType.Thistles, "种子");
chinese.doodad(DoodadType.TorchStand, "火炬台", "");
chinese.doodad(DoodadType.Tree, "树", "");
chinese.doodad(DoodadType.TreeWithBerries, "浆果树", "");
chinese.doodad(DoodadType.TreeWithFungus, "真菌树", "");
chinese.doodad(DoodadType.TreeWithVines, "藤蔓树", "");
chinese.doodad(DoodadType.Vines, "葡萄藤");
chinese.doodad(DoodadType.WhiteMushrooms, "白蘑菇");
chinese.doodad(DoodadType.WildOnion, "野生的洋葱", "");
chinese.doodad(DoodadType.WoodenChest, "木质箱子", "");
chinese.doodad(DoodadType.WoodenDoor, "木质门", "");
chinese.doodad(DoodadType.WoodenDoorOpen, "打开的木质门", "");
chinese.doodad(DoodadType.WoodenFence, "木栅栏", "");
chinese.doodad(DoodadType.WoodenGate, "木质闸门", "");
chinese.doodad(DoodadType.WoodenGateOpen, "打开的木质闸门", "");
chinese.doodad(DoodadType.WoodenWall, "木质墙", "");
chinese.doodad(DoodadType.WroughtIronChest, "铁箱子", "");
chinese.doodad(DoodadType.YellowFlowers, "黄色的花");

// Uses
chinese.use(ActionType.Attack, "攻击", "");
chinese.use(ActionType.Build, "放置", "你可以把这个物品放置在你面前的格子上。");
chinese.use(ActionType.Carve, "切割", "可以用于切开动物的尸体或者去除地上的脏东西。");
chinese.use(ActionType.Cast, "钓鱼", "可以试图投掷该物品抓鱼。");
chinese.use(ActionType.Decode, "解读", "可以试图解读地图的内容，找到宝藏的位置离你多远。");
chinese.use(ActionType.Dig, "挖掘", "可以用于挖掘地面的资源或物品。");
chinese.use(ActionType.Disassemble, "分解", "可以把这个物品分解。");
chinese.use(ActionType.Dismantle, "拆除", "可以把这个物品拆除。");
chinese.use(ActionType.DrawMap, "绘制地图", "可以利用你的技能绘制地图。");
chinese.use(ActionType.Drink, "饮用", "可以饮用以减少你的口渴，但是不干净的水会产生负面效果。");
chinese.use(ActionType.DrinkCure, "饮用治愈", "可以用于治疗中毒，可能还有益健康。");
chinese.use(ActionType.Eat, "食用", "可以减少你的饥饿，口渴，增加你的健康和耐力，但是也可能会减少，取决于你吃的是什么。");
chinese.use(ActionType.Extinguish, "熄灭", "可以用来扑灭火把，熄灭火焰。");
chinese.use(ActionType.Fire, "射击", "你可以使用这把武器进行射击。");
chinese.use(ActionType.Garden, "肥料", "可以增加植物的生长能力，但只能用于某些植物。");
chinese.use(ActionType.Gather, "采集", "可以直接收集你身旁的资源。可以允许它自动收集资源。");
chinese.use(ActionType.GatherTreasure, "收集宝藏", "可以试图在一个已经解密的宝藏地图上收集宝藏，范围取决于你的采矿技能。");
chinese.use(ActionType.GatherWater, "收集水源", "可以把水源装在物品里。");
chinese.use(ActionType.Heal, "医治", "可以恢复你的健康。");
chinese.use(ActionType.Ignite, "点燃", "可以使用这个物品在火源上燃烧。");
chinese.use(ActionType.LockPick, "开锁", "可以把锁住的东西打开。");
chinese.use(ActionType.Open, "打开", "可以打开这件物品，得到新的未知物品。");
chinese.use(ActionType.OpenContainer, "打开容器", "可以打开它把物品丢出降低重量。");
chinese.use(ActionType.Paddle, "航行", "可以在水上航行，不会让你湿透还能保持正常的速度。");
chinese.use(ActionType.Pickup, "捡起", "");
chinese.use(ActionType.Plant, "种植", "可以种植在地面上，有一些植物需要特定的地形或者物品。");
chinese.use(ActionType.Pour, "倾倒", "可以倒在火上以熄灭火，倒在水里过滤，或者倒在植物上增加生长能力，或者只是倒而已。");
chinese.use(ActionType.PourOnYourself, "倒在身上", "可以缓解烧伤。");
chinese.use(ActionType.Preserve, "保鲜", "可以延长食品的腐烂时间。");
chinese.use(ActionType.Read, "阅读", "可以阅读，阅读之后会提供一些知识。");
chinese.use(ActionType.Reinforce, "加固", "可以增加一个受损的物品的耐久，成功率基于你的技能熟练度。");
chinese.use(ActionType.Repair, "修理", "可以修复一个损坏的物品，成功率基于你的技能熟练度。");
chinese.use(ActionType.Rest, "休息", "可以在上面休息一段时间恢复健康和耐力，当你的耐力恢复到良好时，你会停止休息。");
chinese.use(ActionType.SailToCivilization, "驶向文明", "在收集了所有的宝藏之后，你可以回到文明并且沐浴在你的财富和名声的荣耀之中。你可以返回到这片土地。");
chinese.use(ActionType.SetDown, "丢弃", "可以把这个物品丢在你面前的格子上，这个操作可以扑灭火灾。");
chinese.use(ActionType.Shoot, "射击", "你可以用这个物品射箭。");
chinese.use(ActionType.Sleep, "睡觉", "可以在上面睡一段时间，恢复健康和耐力。持续时间由你的露营技能和一天的时长决定，如果旁边有营火之类的火源的话你会不容易感觉到饿和口渴。");
chinese.use(ActionType.Sling, "弹射", "你可以用这个物品射出子弹。");
chinese.use(ActionType.Squeeze, "挤压", "往你面前的方向喷出火。");
chinese.use(ActionType.StartFire, "生火", "可以用来生火，必须有燃料才能成功，可以点亮篝火、炉子、窑炉，如果是需要火种的物品那还需要一个火种。");
chinese.use(ActionType.StokeFire, "维持火源", "可以增加火源的火焰强度。");
chinese.use(ActionType.Teleport, "传送", "当魔杖一挥动，将传送到你前面的位置。");
chinese.use(ActionType.TellTime, "测量时间", "可以测量白天和黑夜的时间。");
chinese.use(ActionType.Throw, "投掷", "");
chinese.use(ActionType.Transmogrify, "变形", "可以对一个装备注入神奇的魔法属性。");
chinese.use(ActionType.TraverseTheSea, "穿越海洋", "可以用于前往新的未开发的土地。");

// Terrain/tiles
chinese.terrain(TerrainType.Ash, "灰烬");
chinese.terrain(TerrainType.BarePalmTree, "光秃秃的棕榈树", "");
chinese.terrain(TerrainType.BareTree, "光秃秃的树", "");
chinese.terrain(TerrainType.CaveEntrance, "洞穴入口", "");
chinese.terrain(TerrainType.Clay, "粘土");
chinese.terrain(TerrainType.ClayBrickFlooring, "粘土砖地板");
chinese.terrain(TerrainType.CobblestoneFlooring, "鹅卵石地板");
chinese.terrain(TerrainType.DeepFreshWater, "深层淡水");
chinese.terrain(TerrainType.DeepSeawater, "深层海水");
chinese.terrain(TerrainType.Dirt, "泥土");
chinese.terrain(TerrainType.FreshWater, "新鲜水");
chinese.terrain(TerrainType.Grass, "草");
chinese.terrain(TerrainType.Gravel, "砾石");
chinese.terrain(TerrainType.PalmTree, "棕榈树", "");
chinese.terrain(TerrainType.PalmTreeWithCoconuts, "椰子棕榈树", "");
chinese.terrain(TerrainType.Rocks, "岩石");
chinese.terrain(TerrainType.RocksWithCoal, "含煤的岩石");
chinese.terrain(TerrainType.RocksWithIron, "含铁的岩石");
chinese.terrain(TerrainType.RocksWithLimestone, "含石灰的岩石");
chinese.terrain(TerrainType.RocksWithTalc, "含滑石的岩石");
chinese.terrain(TerrainType.Sand, "沙子");
chinese.terrain(TerrainType.Sandstone, "砂岩");
chinese.terrain(TerrainType.SandstoneFlooring, "砂岩地板");
chinese.terrain(TerrainType.SandstoneWithIron, "含铁的砂岩");
chinese.terrain(TerrainType.SandstoneWithNiter, "含硝石的砂岩");
chinese.terrain(TerrainType.Seawater, "海水");
chinese.terrain(TerrainType.ShallowFreshWater, "浅层淡水");
chinese.terrain(TerrainType.ShallowSeawater, "浅层海水");
chinese.terrain(TerrainType.Snow, "雪");
chinese.terrain(TerrainType.Swamp, "沼泽");
chinese.terrain(TerrainType.Tree, "树", "");
chinese.terrain(TerrainType.TreeWithBerries, "浆果树", "");
chinese.terrain(TerrainType.TreeWithFungus, "真菌树", "");
chinese.terrain(TerrainType.TreeWithVines, "藤蔓树", "");
chinese.terrain(TerrainType.WoodenFlooring, "木质地板");
chinese.terrain(TerrainType.RedCarpet, "红地毯");

// Events
chinese.tileEvent(TileEvent.Type.Fire, "着火");

// On Equips
chinese.onEquipType(OnEquipType.LightSource, "光源");
chinese.onEquipType(OnEquipType.Telescopy, "望远镜");

// Monsters
chinese.monster(MonsterType.AcidSpitterDemon, "喷酸性口水的恶魔", "");
chinese.monster(MonsterType.Bear, "熊", "");
chinese.monster(MonsterType.Blindfish, "盲鱼", "");
chinese.monster(MonsterType.Bogling, "博格林", "");
chinese.monster(MonsterType.Chicken, "鸡", "");
chinese.monster(MonsterType.ClawWorm, "爪虫", "");
chinese.monster(MonsterType.Cod, "鳕鱼", "");
chinese.monster(MonsterType.Drake, "小龙", "");
chinese.monster(MonsterType.FireElemental, "火元素", "");
chinese.monster(MonsterType.GiantRat, "巨鼠", "");
chinese.monster(MonsterType.GiantSpider, "巨型蜘蛛", "");
chinese.monster(MonsterType.GreyWolf, "灰狼", "");
chinese.monster(MonsterType.Harpy, "女妖", "");
chinese.monster(MonsterType.Hobgoblin, "妖怪", "");
chinese.monster(MonsterType.Imp, "小鬼", "");
chinese.monster(MonsterType.JellyCube, "果冻怪", "");
chinese.monster(MonsterType.Kraken, "海妖", "");
chinese.monster(MonsterType.LivingMushroom, "活菌怪", "");
chinese.monster(MonsterType.LivingRock, "岩石怪", "");
chinese.monster(MonsterType.PirateGhost, "海盗幽灵", "");
chinese.monster(MonsterType.Rabbit, "兔子", "");
chinese.monster(MonsterType.Rat, "老鼠", "");
chinese.monster(MonsterType.Shark, "鲨鱼", "");
chinese.monster(MonsterType.SkeletalMage, "骷髅法师", "");
chinese.monster(MonsterType.Skeleton, "骷髅", "");
chinese.monster(MonsterType.Slime, "软泥怪", "");
chinese.monster(MonsterType.Snake, "蛇", "");
chinese.monster(MonsterType.TimeSkitter, "时光掠影", "");
chinese.monster(MonsterType.TrapdoorSpider, "隐身蜘蛛", "");
chinese.monster(MonsterType.VampireBat, "吸血蝙蝠", "");
chinese.monster(MonsterType.Zombie, "僵尸", "");

// Unique corpse types
chinese.monsterCorpse(MonsterType.FireElemental, "一堆灰烬");
chinese.monsterCorpse(MonsterType.Blood, "血");

// Skills
chinese.skill(SkillType.Chemistry, "化学技能", "对使用化学混合物对工艺产品产生作用的成功率。");
chinese.skill(SkillType.Anatomy, "解剖技能", "提高对某个生物的健康状况描述的准确性。<br />降低出血和中毒的几率。<br />提高医疗品的有效性。<br />增加治愈的成功率。");
chinese.skill(SkillType.Archery, "射击技能", "使用弓和枪支时，增加攻击伤害，精度和最大范围。");
chinese.skill(SkillType.Blacksmithing, "锻造技能", "影响锻造的质量，修理物品的成功率。");
chinese.skill(SkillType.Botany, "种植技能", "提高种植的成功率。<br />提高食用植物时的效果。<br />减少在践踏植物时踩伤它们的几率。");
chinese.skill(SkillType.Camping, "露营技能", "提高临时睡袋的使用效果。<br />提高点火的成功率。");
chinese.skill(SkillType.Cartography, "绘图技能", "提高成功阅读地图的几率。<br />阅读地图时不再那么模糊。");
chinese.skill(SkillType.Claythrowing, "陶冶技能", "影响用粘土制作物品时的质量和成功率。");
chinese.skill(SkillType.Cooking, "烹饪技能", "延长煮熟的物品腐烂时间。");
chinese.skill(SkillType.Fishing, "垂钓技能", "增加成功捕捉鱼的机会。使用钓鱼杆时增加使用的最大范围。<br />增加你可以收集水下的宝藏的范围。");
chinese.skill(SkillType.Fletching, "箭羽技能", "影响制作箭头、弓和吊索时的质量和修复它们。");
chinese.skill(SkillType.Glassblowing, "吹制技能", "影响用玻璃制作工艺物品的质量和成功率。");
chinese.skill(SkillType.Leatherworking, "皮革技能", "影响用皮革制作物品的质量、修理和成功率。");
chinese.skill(SkillType.LockPicking, "撬锁技能", "增加成功解锁箱子的机会。");
chinese.skill(SkillType.Lumberjacking, "伐木技能", "增加伐木时掉落木头的几率。<br />降低伐木时减少耐力的几率。");
chinese.skill(SkillType.Mining, "采矿技能", "增加岩石掉落资源的几率。<br />降低采矿时减少耐力的几率。<br />增加你可以从中收集宝藏的范围。");
chinese.skill(SkillType.Mycology, "菌学技能", "提高种植蘑菇的成功率。<br />提高食用菌类的效果。<br />减少践踏菌类时踩伤它们的概率。");
chinese.skill(SkillType.Parrying, "格挡技能", "增加你的基础防御值。<br />提高在战斗中减少伤害的机会。<br />降低被攻击时降低耐力的几率。");
chinese.skill(SkillType.Stonecrafting, "石艺技能", "影响用石头制作物品的质量和修理的成功率。");
chinese.skill(SkillType.Swimming, "游泳技能", "提高在水上的速度。<br />降低了在水上丢失水分的几率。");
chinese.skill(SkillType.Tactics, "战术技能", "增加基础攻击值。<br />增加命中率。<br />降低减少耐力的几率。");
chinese.skill(SkillType.Tailoring, "剪裁技能", "影响使用布材制作的质量和修理的成功率。");
chinese.skill(SkillType.Throwing, "投掷技能", "增加投掷时的攻击伤害，精度和最大射程。");
chinese.skill(SkillType.Tinkering, "修复技能", "影响使用各种资源和方法制作的物品的质量和修复的成功率。");
chinese.skill(SkillType.Trapping, "诱捕技能", "增加了诱捕生物的伤害和成功率。<br />减少设置陷阱失败的机会，减少陷阱所造成的伤害。");
chinese.skill(SkillType.Woodworking, "木艺技能", "影响用木头制作物品的质量和修复的成功率。");

// Milestones
chinese.milestone(MilestoneType.Abnormalizer, "怪物猎人", "杀死25个异常的生物。");
chinese.milestone(MilestoneType.Chef, "东方厨师", "烹饪25道菜。");
chinese.milestone(MilestoneType.Crafter, "灵巧工匠", "制作250个物品。");
chinese.milestone(MilestoneType.Extincteur, "嗜血狂人", "杀死1000个生物。");
chinese.milestone(MilestoneType.Gardener, "辛勤园丁", "种植50个植物或蘑菇。");
chinese.milestone(MilestoneType.Gatherer, "采集专家", "采集1000次。");
chinese.milestone(MilestoneType.Hunter, "动物猎人", "杀死100个生物。");
chinese.milestone(MilestoneType.Locksmith, "专精锁匠", "锁上10把锁。");
chinese.milestone(MilestoneType.ReaperOfSouls, "海盗克星", "杀死了50个海盗幽灵，并收获他们的尸体。");
chinese.milestone(MilestoneType.Survivor, "生存专家", "存活10000个回合。");
chinese.milestone(MilestoneType.Thrower, "投掷专家", "投掷500个物品。");
chinese.milestone(MilestoneType.Trapper, "陷阱专家", "用陷阱让10个生物受伤。");
chinese.milestone(MilestoneType.TreasureHunter, "宝藏猎人", "挖出10个宝箱。");
chinese.milestone(MilestoneType.Collector, "收藏大师", "收集所有物品。");
chinese.milestone(MilestoneType.Explorer, "探索专家", "踩过所有不同类型的土地。");
chinese.milestone(MilestoneType.Grandmaster, "特级大师", "技能达到100%熟练度。");
chinese.milestone(MilestoneType.Prepared, "全副武装", "在每个装备槽都有装备。");
chinese.milestone(MilestoneType.Doctor, "赤脚医生", "治愈了所有不同类型的伤痛。");
chinese.milestone(MilestoneType.Artificer, "魔法技师", "改变一个物品的属性。");
chinese.milestone(MilestoneType.Seafarer, "大力水手", "航行到文明世界并完成游戏。");
chinese.milestone(MilestoneType.Navigator, "职业驴友", "穿越大海寻找新的土地。");
chinese.milestone(MilestoneType.DragonSlayer, "屠龙勇士", "杀死一只小龙。");
chinese.milestone(MilestoneType.Treasurer, "乡村土豪", "收集五种类型的宝藏。");

// Hints
chinese.hint(HintType.WelcomeToWayward, "任意岛欢迎你!", "欢迎来到任意岛！任意岛当前处于测试阶段，并且会有很多东西会随着我们的更新而改进. 如果你设置了显示提示的话, 像这样的提示窗口会在你玩游戏的时候弹出. 你可以关闭自动提示, 点击下面的 \"禁用提示\" 按钮即可. 如果你需要进一步的帮助或提示, 访问 <a target=\"_blank\" href=\"http://steamcommunity.com/app/379210/discussions/\">Steam讨论论坛</a>.<br /><br />如果你想要始终玩到最新版本的任意岛, 请浏览 <a target=\"_blank\" href=\"http://www.unlok.ca/category/wayward/\">Wayward博客</a>, <a target=\"_blank\" href=\"http://www.unlok.ca/forums/wayward-forum/\">Wayward论坛</a>, 或者 <a target=\"_blank\" href=\"http://www.reddit.com/r/Wayward/\">子页面</a>.<br /><br />想帮助任意岛宣传, 或者访问以下网址: <a target=\"_blank\" href=\"https://www.facebook.com/waywardgame\">Facebook</a>, <a target=\"_blank\" href=\"https://twitter.com/Wayward_Game\">Twitter</a>, 或者 <a target=\"_blank\" href=\"http://www.indiedb.com/games/wayward\">IndieDB</a>.");
chinese.hint(HintType.Controls, "控制", "键位可以在菜单 \"键位\" 里修改.<br /><br /><h3>窗口快捷键</h3><br />{ui.getStringForKeyBind(KeyBind.Escape)} = 关闭菜单和窗口, {ui.getStringForKeyBind(KeyBind.Inventory)} = 物品栏, {ui.getStringForKeyBind(KeyBind.Equipment)} = 装备, {ui.getStringForKeyBind(KeyBind.Crafting)} = 合成, {ui.getStringForKeyBind(KeyBind.Help)} = 帮助, {ui.getStringForKeyBind(KeyBind.Skills)} = 技能, {ui.getStringForKeyBind(KeyBind.Messages)} = 信息, {ui.getStringForKeyBind(KeyBind.Options)} = 选择, {ui.getStringForKeyBind(KeyBind.Actions)} = 操作, {ui.getStringForKeyBind(KeyBind.Milestones)} = 里程碑<br /><br /><h3>移动</h3><br />你可以使用 {ui.getStringForKeyBind(KeyBind.Up)}, {ui.getStringForKeyBind(KeyBind.Left)}, {ui.getStringForKeyBind(KeyBind.Down)}, {ui.getStringForKeyBind(KeyBind.Right)} 或者用鼠标点击游戏屏幕里你想去的方向来移动你的人物。跳过这个回合或者捡起你站着位置的物品, 可以按空格键或者在游戏屏幕里左键点击你的角色来完成。<br /><br /><h3>操作</h3><br />打开操作菜单会有一系列的操作可以让你在相邻的空间或者物品上执行选中的操作; 例如, 不用切割就可以采到一只菠萝.。在操作菜单里也可以选择跳跃, 来让你脱离困境, 但是当心体力的大量减少; 体力的减少会根据你的负重来计算.<br /><br /><h3>使用物品</h3><br />你可以用左击物品弹出菜单来操作它. 你会看到一列你可以执行的操作. 另外, 你可以通过拖放一个物品进快捷栏. 按快捷栏相对应的数字键或者热键 ({ui.getStringForKeyBind(KeyBind.One)}, {ui.getStringForKeyBind(KeyBind.Two)}, {ui.getStringForKeyBind(KeyBind.Three)}, etc.) 可以快速使用这些物品.<br /><br /><h3>物品使用, 放下和信息</h3><br />有些物品有多于一种的用途 - 如果有的话会展示在物品菜单里. 你可以右键点击一个物品来放下它而无需打开物品菜单. 如果你正面对着一个容器, 你可以把物品放进去. 你可以使用shift + 右键 (或者使用菜单里的 \"全部放进去\" 指令) 来把同类的多个物品放下. 不管是物品, 怪物, 方块和其他, 你可以用右键在游戏屏幕里点击你想了解的来查看信息 (称为 \"检查\").<br /><br /><h3>更多信息</h3><br />鼠标悬停在物品上有时候可以获得更多的信息. 物品上将会现实小提示. 鼠标悬停在合成物品上会高亮合成所需物品.<br /><br /><h3>物品管理</h3><br />除了拖放物品进快捷栏, 只要你装备的物品适合该快捷栏, 你也可以照这样装备物品. 拖拽和放下也用于移动物品到你的容器窗口和物品栏 (shift + 拖拽会移动所有相同物品). 另外, 右键点击一样装备列表, 快捷栏或者容器窗口里的物品会把它从那一格转移到物品栏里.");
chinese.hint(HintType.CorpseCarving, "搜刮尸体", "想从这个尸体上收集潜在的资源, 你可以试着用一个尖锐的物体切开它. 在物品菜单选择 \"切开\" 或者你可以把它添加到快捷栏里以方便使用.");
chinese.hint(HintType.Doodads, "道具", "道具就是指那些在地上的物体例如植物, 一堆堆的石头, 炉火, 篝火, 等等. 你可以做以下操作之一来收集它们:<br /><br />1. 面对物品时, 单击或者选择 \"动作\" 快捷键 {ui.getStringForKeyBind(KeyBind.Actions)}, 并选择 \"用手收集物品\" 选项.<br />2. 使用有 \"挖掘\" 的工具比方说一个石铲.<br />3. 使用有 \"切开\" 的工具比方说一个尖锐的石头.<br />4. 使用有 \"收集\" 的工具比方说一个木杆.<br /><br />当你素手没装备工具的时候 (选项 1) 有时候可能会被伤害. 使用工具时 (选项 2/3/4) 会消耗工具的耐久. 有些物品可能需要一个能 \"切开\" 的工具, 例如一个待搜刮的尸体.");
chinese.hint(HintType.CaveDarkness, "洞穴黑暗", "这里可能是藏宝的最好地方, 但是可能首先需要火或者火把照明.");
chinese.hint(HintType.Nightfall, "晚上", "夜幕降临! 找一个安全区域扎营并且准备好战斗吧! 很多猛兽都在晚上觅食.");
chinese.hint(HintType.StaminaReplenishment, "体力补充", "你很累了. 用吊床或者铺盖睡觉或者休息来回复体力吧. 你可以通过进入操作菜单选择 \"休息\" 来休息; 然而, 使用合适的物品休息将会有更好的回复作用. 休息和睡觉是不同的, 睡觉是你只能休息直到你的体力补满. 或者, 你可以按住空格键或者点选你的角色来跳过这些回合.");
chinese.hint(HintType.HealthProblems, "健康问题", "你伤得很重, 使用食物或者恢复健康的物品来回血. 一些状态效果将降低你的恢复能力, 其中包括出血和中毒. 另外, 你也可以尝试睡觉或休息来回血..");
chinese.hint(HintType.Bleeding, "出血", "你在出血! 这个状态经常出现在简陋的手术或者跟猛兽搏斗之后. 请使用治疗物品来停止出血, 例如绷带或止血带. 出血会导致你饥饿/口渴的速度加快, 体力恢复减慢, 并且不再回血.");
chinese.hint(HintType.Poisoned, "中毒", "你中毒了! 中毒可以来自吃了不好的东西或者某种生物. 请使用治疗物品来治愈中毒, 例如一瓶药水. 中毒会导致你饥饿/口渴的速度加快, 体力恢复减慢, 并且不再回血.");
chinese.hint(HintType.Dehydration, "脱水", "你脱水了. 有很多方法来获得可饮用的水, 但是不幸的是, 最大的水资源, 海水是几乎不可以直接饮用的. 你需要蒸馏淡化水, 喝起来才不会有不良效果. 或者, 你可以找一个淡水资源, 例如从洞穴里, 小湖泊, 沙漠绿洲, 沼泽地或者池塘可以找到. 淡水可以直接饮用而不会有太多的不良效果; 然而, 煮过的水还是最安全的.");
chinese.hint(HintType.UseATool, "使用工具", "徒手收集资源困难而且会损伤; 装备或使用工具来避免受伤. 如果你在挖矿或者伐木, 你的武器攻击值也会帮助你更快地采集物品. 钝系武器会帮你更快地挖掘, 锋利的武器会帮你更快地砍伐.");
chinese.hint(HintType.Durability, "耐久度", "你的工具, 武器或防具在过度使用的时候会很快破碎. 如果你没有找到或合成一个物品来修复它, 它将彻底坏掉.");
chinese.hint(HintType.Death, "死亡", "死亡是永久的. 虽然你死了, 但所有你发现过的合成配方在你下次游玩的时候将可以直接使用. 你的里程碑们也可以继承, 给你提供多种开局福利.");
chinese.hint(HintType.ConsumingBadThings, "吃下不好的东西", "噢! 吃东西也会伤害你! 不是所有可以吃的/可以喝的东西都是用来吃喝的, 至少在不知道后果的时候不应该吃. 从另一个角度, 有时候为了获得物品的其他好的状态, 冒险吃下是值得的. 吃下不好的东西有时候会导致中毒.");
chinese.hint(HintType.FastPickup, "快速捡起", "你刚刚建起了一个地上的物品. 有时候有多个物品堆成一堆. 按着空格键或者单击你的角色可以让你不用移动就收集到物品.");
chinese.hint(HintType.Bugs, "出错了!", "你发现了一个错误? 可以让我们知道发生了什么吗, 我们才可以阻止这个问题再次发生在其他玩家身上? 你可以通过发布一个帖子在 <a target=\"_blank\" href=\"http://steamcommunity.com/app/379210/discussions/1/\">Steam Discussions Bug Reports forum</a>.");
chinese.hint(HintType.HeldItems, "手持道具", "你的左右手装备栏是可以更换的. 你可以装备两个武器, 两个工具, 两个盾或者任意两个的组合. 当心不要在收集或者攻击的时候损坏了有用的装备例如火把或者盾牌. 如果想要攻击或者收集资源, 经常确保在另一个手上装备另一种武器或工具, 以免损坏火把. 你可以使用双手战斗, 所以如果可能的话, 双手都装备上是很重要的.");
chinese.hint(HintType.Milestones, "里程碑", "里程碑是有个人特色的目标和成就. 每次游玩, 你都被给予了探索和工作的目标数目. 里程碑在你每次游玩或者死亡后都会保存. 你完成了越多, 每次开场能获得的技能, 技能点和开场道具就会越多.");
chinese.hint(HintType.Burned, "烧伤", "你被烧了! 这种持续的伤害和疼痛可能是由于没保护的情况下碰到了火焰, 或者其他原因造成. 往自己身上倒液体会平息伤和疼痛. 或者你可以到深海游个泳. 保持在水里直至状态平复. 持续被烧而不治疗会让你有一段时间无法回血.");
chinese.hint(HintType.Crafting, "合成", "合成很简单, 但是有很多规则!<br /><br />当鼠标悬停在合成窗口的一个物品上时, 你可以看到物品栏里合成中将会使用到的物品被高亮边框框起来了. 你也会发现在必须物品里你会使用到排序的第一个. 可以拖动物品栏里物品的顺序或者排序来在合成里使用不同物品.<br /><br />在合成中使用低耐久度的东西将会印象到合成后物品的耐久度. 另外, 在合成中使用卓越品质, 特殊品质或者传奇品质的物品将提升合成后出现特殊品质的几率. 如果使用高品质的物品来合成, 会腐败的物品 (例如食物) 将会有耐久奖励.<br /><br />你会在收集必须物品以及找远古教学卷轴的时候发现新的合成方法.");
chinese.hint(HintType.Encumbered, "过度负重", "你背了太多东西, 导致移动速度降低和停止回血. 再继续负重, 尝试走路的话你会因为负重过度而开始掉血. 你可以通过鼠标右击, 从物品菜单, 或者拖拽到游戏屏幕来把从物品栏里扔掉它们.");
chinese.hint(HintType.DailyChallengeMode, "每日挑战模式", "每日挑战模式是一个更难的游戏模式, 它有着一些特殊的游戏规则来给熟练的玩家增加挑战性. 你可以期待更多的怪物, 更难的游戏开局, 等等. 在这个模式里你不能保存你的游戏. 世界和随机性每天都是唯一的, 允许多位玩家在同一环境下游玩.");
chinese.hint(HintType.MovingItems, "移动项目", "在游戏里有很多种方法来排列和移动项目<br /><br />1. 拖拽和释放. 你可以把一个项目拖放到容器窗口, 快速栏, 装备栏, 或者直接放在地上, 把它拖到想要的位置上. 拖放到游戏窗口可以把它放在你的面前, 或者放到你面前的箱子里. 按着shift来拖拽会移动所有同类的物品<br />2. 从物品菜单. 鼠标左键选择一个物品会展示该物品菜单, 其中有放下/放下全部的选项, 如果开着一个容器窗口, 会出现移动/移动全部的选项. 如果你点击了特殊品质的物品, 会看到附加放下/移动所有相同质量的选项.<br />3. 右键/放下. 你可以右键物品栏的任何项目来把它放下在你的面前. 如果你面对着一个箱子, 这个操作会使它自动放进箱子里. 按着shift的同时使用鼠标右键的话会放下所有同类的物品.");
chinese.hint(HintType.CraftingFailure, "合成失败", "在游戏里的所有合成都会有相关的技能等级. 尝试每个合成会提升该物品的合成技能等级. 这些等级从简单到难分别为: 简单, 中级, 高级, 以及专家.<br /><br />尝试合成一个比你掌握的合成等级更高等级的物品可能导致失败. 你会有机会成功合成出来, 你的技能等级会上升. 如果物品的技能等级以橙色表示, 你将有低概率成功地合成它.");
chinese.hint(HintType.Malignity, "恶意", "这些土地是神秘的, 似乎会对你的存在和行为有反应. 合成物品, 杀死生物, 使用道具或者使用技能都会增加或者减少你的恶意. 你的恶意越高, 生存挑战会变得越难. 保持一个低水平或者平均水平的恶意呈现了你爱好和平, 这些土地会对你仁慈并不会出现更多的难对付生物. 有些和平的举动会降低恶意级别例如园艺, 种植蘑菇或者植物. 用船旅行到其他土地会显著地降低恶意值.");
        Languages.add(chinese);
    };
    Mod.prototype.onLoad = function (saveData) {
    };
    Mod.prototype.onUnload = function () {
    };
    Mod.prototype.onSave = function () {
    };
    return Mod;
}(Mods.Mod));